spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/mall_fei?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&connectTimeout=5000&socketTimeout=10000
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

springdoc:
  api-docs:
    enabled: true

mall:
  order:
    timeout-minutes: 15
  pay:
    alipay:
      enabled: true
      # 正式环境网关；如果你要沙箱联调可改回 openapi-sandbox.dl.alipaydev.com
      gateway: https://openapi.alipay.com/gateway.do
      app-id: 2021005183677257
      # 这里请直接填你的应用私钥（PKCS8）
      merchant-private-key: |
        请替换为你的支付宝应用私钥
      alipay-public-key: |
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnfNnoFv2MRT6xizw
        4VkfY1LUuh6kb4uvxQ7EvM82e76H64vbrfX1Ii9sz8+4EqNh8A4FFu9M8rM5
        qfJm+cj+6x2MxjVgNxEiJ1VxM9HB+I7DvyM6m6xwUSa7vPjmx0UmyiQe2ciG
        xdB+fN4R4CNj0Y6hjfKxQtiE5U6TM7G+eTSUN7VHzt3m1elQQvV2yzxprzJh
        gYo0RW22jTXVYTHmR8xWc6q14Y8Rzwo5nMY2WN8hSI8B9qy3Q39sVhV5j6vM
        0kIq3JcS3p6SkcQ2Q9zDKGyUL3Jc7xvWNo7fGwxyAzIW6frs66g6xnI5nS3q
        Anz4gY13lQIDAQAB
      notify-url: https://your-local-tunnel-domain/api/pay/callback/alipay
      return-url: https://your-local-tunnel-domain/api/pay/alipay/return-bridge
      client-return-url: https://your-local-tunnel-domain/pay/return
      sign-type: RSA2
      charset: UTF-8
      format: json
  user:
    alipay-login:
      redirect-uri: https://your-local-tunnel-domain/api/users/login/alipay/callback
      frontend-redirect-uri: https://your-local-tunnel-domain/login
      state-expire-seconds: 300
      login-ticket-expire-seconds: 120
