spring:
  datasource:
    url: jdbc:mysql://${MALL_MYSQL_HOST:127.0.0.1}:${MALL_MYSQL_PORT:3306}/${MALL_MYSQL_DATABASE:mall_fei}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&connectTimeout=5000&socketTimeout=10000
    username: ${MALL_MYSQL_USERNAME:root}
    password: ${MALL_MYSQL_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

springdoc:
  api-docs:
    enabled: true

mall:
  order:
    timeout-minutes: 15
  file:
    storage-type: local
    upload-dir: /home/ubuntu/storage
    public-base-path: /uploads
    max-avatar-size: 2097152
  pay:
    alipay:
      enabled: true
      gateway: https://openapi-sandbox.dl.alipaydev.com/gateway.do
      app-id: 9021000163654371
      merchant-private-key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDZeFrKAfvVENOGY9jmj3SI+eoR9Xbo4GWZm7iexu+eoZQinJuJfSmZ8BAhc2E85LVlvpRjt4AjqZNd+hvQ1P7JZWrFSy8XzuZiT07PRrk17RWAHBAv0CC02HhZC8L6jaYmpJfj0w+EUCnUlHNNK1N44UUsjNq6x+SKEy7uLUHCtA7hubeLYqt5WSz09mlyhP8Js+sjSytdqeEjYvc6cnnKKdKevaqSqxSTlbq9KI/Md190kQjMH1Cn+VeM6yrBQLggJcxe2B43yVyRPx/i/zxBtCKfXKw0lXPID/TBKzTFpDmJjIQYMfAbnTdhcYnQORoyta6ulgz5/7Al0oi7/4UlAgMBAAECggEBAKfa7vDHUTMnFq2/edaUWdW0WMhd19duBN3oxTrAwImHnAiPKrqXwjmQg1LedOqEecM7s9u38o8UP6wk9b1d+f9HaX85RfMxfr/ZCTKSGzkVcyf8AT52fhg4kcPhgTDVjq57EsYFzg9JtM/heZHR5E8ESdlWKypKSguNPQcYJY768XGCtKZoZEjeSo7XinR8B6W/pj0EV4i/8OxHOIyr9pFIo9CZqlqVzox3hmH8IzcakOwSv/Uff77WP0VhMsfxaDZkOggfEN0bqNpriJlVY2Tbnx186GfWglDH+d0UrkFPuFF3hhOzqwVdEzlBOTkS7sBhuSUr9G5GU8Gzke9c860CgYEA9z0ZBsfMk/LQ+Ka+opQxnopuCt6RBlRcoqbCrkbPKNUelQSysWnwwHzGkZ7Gt/+JLi7MAy/onEJAZ9iJAQ5qwfq0YWJ8jOLJ0lJLOeh57SzF5IfyZ8AtnfPAwRszzOXXJRBzpOUI9RC5mziTR49I/0qIBFinidmN1CCPXMlkFM8CgYEA4S0z07kuXMqNGycaQCzph6YG55u5Zd/sHTDXDwqpdXWcuP4fYjhEyn1r4PrIL7CkSNpCh4GQ+s0lDKd7Ktyhw4TnCJeXgfyhDierz/hLRznmTWPBygpjOBP4/jYN8JOHssyChzy0vaPLl/Uf2rVbApVM7aJzR2nP7y45BtEn68sCgYBbpjRuxQXbGjnI0tb8IX87TAl60gJknEUyriqgu/LzKf2KNBGhnqn2UMqzFG6JqppJmmNaExphQlXpqOUwlQ2SFsNjDkUpXLB/3K2yK7F28A/zpUmAmEbQtJkRfGn5XIIiZTTZPWXSon6LQa+m6UCgEhrVsZ95hEIFDoTWWnlVFQKBgQCBTVSicobl78XhXq3bRi7/nt3+J1Tp5BCQnpgP4h52/Yd2Ty60Vv1hjW3iLf/AKt3bm8FyUHtxGVX6Ez5N2Y3mWS3VqD7u/KN7HlqxvLF1gBD4RZ1lKFvbOtTTHTUZ/Y2BpaAaikh7UVA6vR6Cl3tgW11mY89wpZkqjk9e08HpywKBgQCl7L7HeLQ72XJI71dsIl7QvPsMO4JArc5YVSqGZ3+iEN0pQg2yuqeIPwGg8mY6s8GXv/Pvej3tt03aYPUCyyg8+vLWsWVdUJ0+6m2/souv395q0p5jCqRkvg6rnE562U9S5yRJLQneYVy7NcJNA05+hxeP8kisvODxCj/sQf4RqA==
      alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApz/DiTR0/iX5VO8JMzNtPBQFU97AZRhWFngyaLXLapxpLV6mt841zieMQ6/m1KvQmByhnDF9u27OYNe2keXNHLqPQr1MV6Yf9j574YK0QwcA8wB1H0k3O6uGxrx/9x9J6+GyAaLJ/uTWJnhhVt7rzUm/bKgQWb7VO0QancwSHnJr3xGZclVB2FDN6gsklKhPgZVG0R7bpswR7IIHMy2W7TQn064eMaUY6a8rqgli/sTsu3fV76yxYLSV9IAKzlUgg5Gp0L72m+7sYeNGgi9CnT7uFeVuwrJrI1XSQTgaStmdY1lEnA9UOd4V5zXSeKKeUQ2qH4OyR6elUofplxahrQIDAQAB
      notify-url: https://mallfei.cloud/api/pay/callback/alipay
      return-url: https://mallfei.cloud/api/pay/alipay/return-bridge
      client-return-url: https://mallfei.cloud/pay/return
      sign-type: RSA2
      charset: UTF-8
      format: json
  user:
    alipay-login:
      gateway: ${MALL_USER_ALIPAY_GATEWAY:https://openapi.alipay.com/gateway.do}
      app-id: ${MALL_USER_ALIPAY_APP_ID:2021006154600932}
      merchant-private-key: ${MALL_USER_ALIPAY_PRIVATE_KEY:MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCPBTaSoXKRuTnXj/NBq4EviEPEvwdPepkGl7ltLrEzUzt7WCL4U/3BSytAx8fGUDE4XObllNOCCwjzWVu0yLXzr8puJvejXhyBrdw4/MzIgpRWsz0a5mfSOJGOPV8QcK1pV0Sg20EvcuZt/qdz4+1q+tIQiyDg0wEPqhHo7GSdcBT0fHEMMl8NCjk00VUJG5pqQGw6mWkJ0ZGvd2preeB8yRN7SDldLAiN0HEiHHfahc1oZ5nEb08LllAtZhKH4zn1q0AVM/HWVlqx3+s9I3rpgADdlG0zv/jlpfPaxlOJeznX065mNeQz0paHu5DP0Qq80Tes+NPl8WOykh2ikjdTAgMBAAECggEAHRpaeIwR3EVs18ibH4nex+VapPaabjnsWcMWIHmX5XHScM8GjrHIuUSqkIwWwuwel/GPqrgWMig8sghE+Qy+uc/TyYZ0bfIAqwLOBWqr4UFxHhNrI8Yu6kBInkEuzxGeuAjiFjmHkjg3W7quKI8BCPvxMxycnCNT2/QnoNY5wy90LdvaFhI7+S9ruKSZNtn0kspeRsDEex+h2F33I6YK1dXcvl3Q7fCO70xKbkY8FHwFKxa5EPsCYZxqqqSJdXxc6KkFcZt436mc2OAWw5VxUMZEv9gcqEWC54XqnqjK9TD6cT53wMn6sMnXd7rVRk651Qtgv035/m3N5l2zlHm6gQKBgQDpJmoCk3k/e+T1X9YopHYMSw9D4gmGBApGVFeldidsehql1IMwBdbRye8GWf7XIRVt4vv+LZ4LoF1Ktz1sGcO5+or3rSgG5hWQsKhmVpsJI4Dk7THN5LnTVDbuZp+ZQU9Y0MvvDBXQ30akhnJZIx1+Y8o5nk7DaCptrZbkKRZjCwKBgQCdCYCyAVEeHoSJjRrF5W40WKWyOsm4aMBxIk6eEwPa09RPeH8FvKj4HJToC4UWnQbW3JKwLFDQnSfknaQx1Q5oY3B7fpqJNU/Alton66xwbO8veoEYnv3yVTgAmvBVRaOEOpywxvkAiqtsD/wHleV0oC72exvVlvdn40fRd2Kp2QKBgGQGCuzX/+hwaqWqW+JLzCkx+naQ/qz0BsRtYryll/w91jjWlwF/P8346Aa9jUsV8m+WNa2yPF+YiO2I91ztIL8k8YGYU9fB1fahE130QccF6EJOUFOYkPBM7NQSSt4g2r2rthH0CVf2sgPbeisrmXejsBpQBFJo2er70gRIbEZJAoGABSMqcqhYXwPgkh9roM3ArTW5Nft2XfIPWaQlrkYw+hez+mWWwjlJzdQhivXVhMfeUWkl412Px0Nc6r29gWPW9NNL+r5Jj/OOiF5nBKdRHNxzdrorPwL0i9j93Ac1lZSRpOHF/oKD4uCmewKK3DSrLQWQg7/DSVmG/n8Q+mlNcQECgYA0J9Hvr0AT6TndObPKRjEz07UeYZ9lgAFbjGXStrUA/a3N8y9QP7LuI9ICKGvhNeRo4C/jBMi/4S/OnH6hBvZBPTj2AYLFg+mabgx5SXCCkhu9RP71ngZIQOWVBQ7FuDXg2/PkHK4dk1b1gdRl/S3RtE1Ly6NPj58yFm5ew4XotQ==}
      alipay-public-key: ${MALL_USER_ALIPAY_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjCBgQacB+3/s+1Ebz/FKzbsQH1wsLJKM5QytlyicJlhodj8e0d3hhdFDBDZoAe+Kxk4pX04SM+3kr/wL3Zzxlo9vTN+zNVw5HCP+1ZxlS/bmDG1qA6N41eFB5bTWqOvbrqxjQ28PmXBwU/MuoBvsXIeIUD0MuVWcf7FJeY8NlJhZvRMaQVuiGErAPcr4MAI0H0N0W4wV2TOQ5renXh4fnC+EqPoh6pz2sfFS2hsuOuxq8HV8PjMO+G9ASwIdSrAv91jcfDMbbNwFstxAuGzF5KxX/OH/gDFC+46AqDpdRpiIVcqzEwvYn9uZJ2ceXhb78xj0yyiznZmbpiteUMwj2wIDAQAB}
      sign-type: RSA2
      charset: UTF-8
      format: json
      redirect-uri: https://mallfei.cloud/api/users/login/alipay/callback
      frontend-redirect-uri: https://mallfei.cloud/alipay-landing
      state-expire-seconds: 300
      login-ticket-expire-seconds: 120
