package com.mallfei.admin.controller;

import com.mallfei.admin.application.dto.*;
import com.mallfei.admin.application.service.*;
import com.mallfei.admin.application.vo.*;
import com.mallfei.common.api.*;
import com.mallfei.common.auth.*;
import com.mallfei.pay.application.vo.PayOrderView;
import com.mallfei.product.application.dto.*;
import com.mallfei.product.application.vo.*;
import com.mallfei.product.domain.model.Category;
import com.mallfei.product.facade.ProductFacade;
import com.mallfei.stock.application.vo.StockConsistencyCheckView;
import com.mallfei.stock.facade.StockSnapshot;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

@RestController
@RequestMapping("/api/admin")
@Validated
@Tag(name = "Admin Backend")
public class AdminController {
    private final AdminApplicationService app;
    private final AdminQueryApplicationService query;
    private final AdminCommandApplicationService command;
    private final AdminAccountManagementApplicationService account;
    private final AdminStockManagementApplicationService stock;
    private final AdminPayManagementApplicationService payManagement;
    private final AdminAftersaleManagementApplicationService aftersaleManagement;
    private final AdminProductManagementApplicationService productManagement;
    private final AdminUserManagementApplicationService userManagement;
    private final AdminOperationConfigApplicationService operationConfig;
    private final AdminOnlineReconciliationApplicationService onlineReconciliation;
    private final ProductFacade product;

    public AdminController(AdminApplicationService app,
                           AdminQueryApplicationService query,
                           AdminCommandApplicationService command,
                           AdminAccountManagementApplicationService account,
                           AdminStockManagementApplicationService stock,
                           AdminPayManagementApplicationService payManagement,
                           AdminAftersaleManagementApplicationService aftersaleManagement,
                           AdminProductManagementApplicationService productManagement,
                           AdminUserManagementApplicationService userManagement,
                           AdminOperationConfigApplicationService operationConfig,
                           AdminOnlineReconciliationApplicationService onlineReconciliation,
                           ProductFacade product) {
        this.app = app;
        this.query = query;
        this.command = command;
        this.account = account;
        this.stock = stock;
        this.payManagement = payManagement;
        this.aftersaleManagement = aftersaleManagement;
        this.productManagement = productManagement;
        this.userManagement = userManagement;
        this.operationConfig = operationConfig;
        this.onlineReconciliation = onlineReconciliation;
        this.product = product;
    }

    @Operation(summary = "管理员密码登录")
    @PostMapping("/login/password")
    public ApiResponse<AdminLoginResult> login(@Valid @RequestBody AdminPasswordLoginRequest req) { return ApiResponse.success(app.login(req)); }
    @RequireAdmin @Operation(summary = "管理员退出登录") @DeleteMapping("/logout") public ApiResponse<Boolean> logout() { app.logout(); return ApiResponse.success("退出成功", Boolean.TRUE); }
    @RequireAdmin @Operation(summary = "获取当前管理员信息") @GetMapping("/me") public ApiResponse<AuthenticatedPrincipal> me() { return ApiResponse.success(app.currentAdmin()); }
    @RequireAdmin @Operation(summary = "修改个人资料") @PutMapping("/me/profile") public ApiResponse<AuthenticatedPrincipal> updateMyProfile(@Valid @RequestBody AdminUpdateProfileRequest req) { return ApiResponse.success(app.updateProfile(req)); }
    @RequireAdmin @Operation(summary = "修改个人密码") @PutMapping("/me/password") public ApiResponse<Boolean> changeMyPassword(@Valid @RequestBody AdminChangePasswordRequest req) { return ApiResponse.success(app.changePassword(req)); }
    @RequireAdmin @RequirePermission("dashboard:view") @Operation(summary = "获取后台看板数据") @GetMapping("/dashboard") public ApiResponse<AdminDashboardOverviewView> dashboard(@RequestParam(required = false) Integer hotSalesThreshold, @RequestParam(required = false) Integer lowSalesThreshold) { return ApiResponse.success(query.dashboardOverview(hotSalesThreshold, lowSalesThreshold)); }
    @RequireAdmin @RequirePermission("dashboard:view") @Operation(summary = "获取财务累计总净收入") @GetMapping("/dashboard/finance-cumulative-net-income") public ApiResponse<java.util.Map<String, Long>> financeCumulativeNetIncome() { return ApiResponse.success(query.financeCumulativeNetIncome()); }
    @RequireAdmin @RequirePermission("dashboard:view") @Operation(summary = "获取近7日财务资金与对账风险趋势") @GetMapping("/dashboard/finance-trend") public ApiResponse<java.util.List<AdminDashboardFinanceTrendView>> financeTrend() { return ApiResponse.success(query.financeTrend()); }
    @RequireAdmin @RequirePermission("dashboard:view") @Operation(summary = "获取近7日仓储库存健康与发货压力趋势") @GetMapping("/dashboard/warehouse-trend") public ApiResponse<java.util.List<AdminDashboardWarehouseTrendView>> warehouseTrend() { return ApiResponse.success(query.warehouseTrend()); }

    @RequireAdmin @RequirePermission("admin:view") @Operation(summary = "查询运营账号列表") @GetMapping("/accounts") public ApiResponse<PageResult<AdminAccountView>> accounts(@RequestParam(required = false) String keyword, @RequestParam(required = false) String roleCode, @RequestParam(required = false) String status, @RequestParam(defaultValue = "1") long page, @RequestParam(defaultValue = "20") long size) { return ApiResponse.success(account.listAccounts(keyword, roleCode, status, page, size)); }
    @RequireAdmin @RequirePermission("role:view") @Operation(summary = "查询内置角色列表") @GetMapping("/roles") public ApiResponse<java.util.List<AdminRoleView>> roles() { return ApiResponse.success(account.roles()); }
    @RequireAdmin @RequirePermission("permission:view") @Operation(summary = "查询权限目录") @GetMapping("/permissions") public ApiResponse<java.util.List<AdminPermissionView>> permissions() { return ApiResponse.success(account.permissions()); }
    @RequireAdmin @RequirePermission("permission:view") @Operation(summary = "查询角色权限模板") @GetMapping("/accounts/permission-templates") public ApiResponse<java.util.Map<String, java.util.List<String>>> permissionTemplates() { return ApiResponse.success(account.permissionTemplates()); }
    @RequireAdmin @RequirePermission("admin:create") @Operation(summary = "创建运营账号") @PostMapping("/accounts") public ApiResponse<AdminAccountView> createAccount(@Valid @RequestBody AdminCreateAccountRequest req) { return ApiResponse.success(account.createAccount(req)); }
    @RequireAdmin @RequirePermission("admin:update") @Operation(summary = "分配运营角色") @PatchMapping("/accounts/{adminId}/role") public ApiResponse<AdminAccountView> assignRole(@PathVariable Long adminId, @Valid @RequestBody AdminAssignRoleRequest req) { return ApiResponse.success(account.assignRole(adminId, req)); }
    @RequireAdmin @RequirePermission("admin:disable") @Operation(summary = "禁用运营账号") @PatchMapping("/accounts/{adminId}/disable") public ApiResponse<AdminAccountView> disableAccount(@PathVariable Long adminId) { return ApiResponse.success(account.disableAccount(adminId)); }
    @RequireAdmin @RequirePermission("admin:disable") @Operation(summary = "启用运营账号") @PatchMapping("/accounts/{adminId}/enable") public ApiResponse<AdminAccountView> enableAccount(@PathVariable Long adminId) { return ApiResponse.success(account.enableAccount(adminId)); }
    @RequireAdmin @RequirePermission("permission:assign") @Operation(summary = "更新运营账号权限") @PutMapping("/accounts/{adminId}/permissions") public ApiResponse<AdminAccountView> updatePermissions(@PathVariable Long adminId, @Valid @RequestBody AdminUpdateAccountPermissionRequest req) { return ApiResponse.success(account.updatePermissions(adminId, req)); }
    @RequireAdmin @RequirePermission("user:view") @Operation(summary = "查询C端用户列表") @GetMapping("/users") public ApiResponse<PageResult<AdminUserListItemView>> users(@RequestParam(required = false) String keyword, @RequestParam(required = false) String status, @RequestParam(required = false) String sortBy, @RequestParam(required = false) String sortOrder, @RequestParam(defaultValue = "1") long page, @RequestParam(defaultValue = "20") long size) { return ApiResponse.success(userManagement.users(keyword, status, sortBy, sortOrder, page, size)); }
    @RequireAdmin @RequirePermission("user:view") @Operation(summary = "查询C端用户详情") @GetMapping("/users/{userId}") public ApiResponse<AdminUserDetailView> userDetail(@PathVariable Long userId) { return ApiResponse.success(userManagement.userDetail(userId)); }
    @RequireAdmin @RequirePermission("user:disable") @Operation(summary = "禁用C端用户") @PatchMapping("/users/{userId}/disable") public ApiResponse<AdminUserDetailView> disableUser(@PathVariable Long userId) { return ApiResponse.success(userManagement.disableUser(userId)); }
    @RequireAdmin @RequirePermission("user:disable") @Operation(summary = "启用C端用户") @PatchMapping("/users/{userId}/enable") public ApiResponse<AdminUserDetailView> enableUser(@PathVariable Long userId) { return ApiResponse.success(userManagement.enableUser(userId)); }
    @RequireAdmin @RequirePermission("log:operation:view") @Operation(summary = "查询运营操作日志") @GetMapping("/operation-logs") public ApiResponse<PageResult<AdminOperationLogView>> operationLogs(@RequestParam(required = false) String keyword, @RequestParam(required = false) String module, @RequestParam(required = false) String result, @RequestParam(required = false) String sortBy, @RequestParam(required = false) String sortOrder, @RequestParam(defaultValue = "1") long page, @RequestParam(defaultValue = "20") long size) { return ApiResponse.success(account.operationLogs(keyword, module, result, page, size, sortBy, sortOrder)); }

    @RequireAdmin @RequirePermission("order:view") @Operation(summary = "查询后台订单列表") @GetMapping("/orders") public ApiResponse<PageResult<AdminOrderSummaryView>> orders(@RequestParam(required = false) String status, @RequestParam(required = false) String keyword, @RequestParam(required = false) java.time.LocalDate startDate, @RequestParam(required = false) java.time.LocalDate endDate, @RequestParam(required = false) String sortBy, @RequestParam(required = false) String sortOrder, @RequestParam(defaultValue = "1") long page, @RequestParam(defaultValue = "10") long size) { return ApiResponse.success(query.adminOrders(status, keyword, startDate, endDate, page, size, sortBy, sortOrder)); }
    @RequireAdmin @RequirePermission("order:view") @Operation(summary = "获取后台订单详情") @GetMapping("/orders/{orderNo}") public ApiResponse<AdminOrderDetailView> orderDetail(@PathVariable String orderNo) { return ApiResponse.success(query.adminOrderDetail(orderNo)); }
    @RequireAdmin @RequirePermission("order:sku:switch") @Operation(summary = "查询订单同商品可切换SKU") @GetMapping("/orders/{orderNo}/items/{orderItemId}/sku-switch-options") public ApiResponse<java.util.List<AdminOrderSkuSwitchOptionView>> orderSkuSwitchOptions(@PathVariable String orderNo, @PathVariable Long orderItemId) { return ApiResponse.success(query.orderSkuSwitchOptions(orderNo, orderItemId)); }
    @RequireAdmin @RequirePermission("order:close") @Operation(summary = "后台取消订单") @DeleteMapping("/orders/{orderNo}") public ApiResponse<AdminOrderDetailView> cancelOrder(@PathVariable String orderNo) { return ApiResponse.success(command.cancelOrder(orderNo)); }
    @RequireAdmin @RequirePermission("order:ship") @Operation(summary = "后台发货") @PatchMapping("/orders/{orderNo}/ship") public ApiResponse<AdminOrderDetailView> shipOrder(@PathVariable String orderNo) { return ApiResponse.success(command.shipOrder(orderNo)); }
    @RequireAdmin @RequirePermission("order:ship") @Operation(summary = "后台完结订单") @PatchMapping("/orders/{orderNo}/complete") public ApiResponse<AdminOrderDetailView> completeOrder(@PathVariable String orderNo) { return ApiResponse.success(command.completeOrder(orderNo)); }
    @RequireAdmin @RequirePermission("order:receiver:update") @Operation(summary = "后台修改订单收货地址") @PutMapping("/orders/{orderNo}/receiver") public ApiResponse<AdminOrderDetailView> updateOrderReceiver(@PathVariable String orderNo, @Valid @RequestBody AdminOrderReceiverUpdateRequest req) { return ApiResponse.success(command.updateReceiver(orderNo, req)); }
    @RequireAdmin @RequirePermission("order:exception:handle") @Operation(summary = "处理订单异常") @PostMapping("/orders/{orderNo}/exception-handle") public ApiResponse<AdminOrderOperationResultView> handleOrderException(@PathVariable String orderNo, @Valid @RequestBody AdminOrderExceptionHandleRequest req) { return ApiResponse.success(command.handleException(orderNo, req)); }
    @RequireAdmin @RequirePermission("order:payment-exception:handle") @Operation(summary = "标记支付异常") @PostMapping("/orders/{orderNo}/payment-exception") public ApiResponse<AdminOrderOperationResultView> markOrderPaymentException(@PathVariable String orderNo, @RequestBody(required = false) java.util.Map<String, String> req) { return ApiResponse.success(command.handleException(orderNo, new AdminOrderExceptionHandleRequest(null, null, null, null, null, null, "PAYMENT_EXCEPTION", null, null, null, null, req == null ? null : req.get("note")))); }
    @RequireAdmin @RequirePermission("order:payment-exception:handle") @Operation(summary = "核验支付异常") @PostMapping("/orders/{orderNo}/payment-exception/verify") public ApiResponse<com.mallfei.pay.application.vo.PayOrderPaymentVerificationView> verifyOrderPaymentException(@PathVariable String orderNo) { return ApiResponse.success(command.verifyPaymentException(orderNo)); }
    @RequireAdmin @RequirePermission("order:payment-exception:handle") @Operation(summary = "支付异常转支付同步状态") @PostMapping("/orders/{orderNo}/payment-exception/transfer-pay-sync") public ApiResponse<com.mallfei.pay.domain.model.PayReconciliationRecord> transferOrderPaymentExceptionToPaySync(@PathVariable String orderNo, @RequestBody(required = false) java.util.Map<String, String> req) { return ApiResponse.success(command.transferPaymentExceptionToPaySync(orderNo, req == null ? null : req.get("note"))); }
    @RequireAdmin @RequirePermission("order:payment-exception:handle") @Operation(summary = "标记支付异常待处理需求") @PostMapping("/orders/{orderNo}/payment-exception/pending-action") public ApiResponse<com.mallfei.pay.domain.model.PayReconciliationRecord> markOrderPaymentExceptionPendingAction(@PathVariable String orderNo, @RequestBody java.util.Map<String, String> req) { return ApiResponse.success(command.markPaymentExceptionPendingAction(orderNo, req == null ? null : req.get("action"), req == null ? null : req.get("note"))); }
    @RequireAdmin @RequirePermission("order:confirm-paid") @Operation(summary = "人工确认已支付") @PostMapping("/orders/{orderNo}/confirm-paid") public ApiResponse<AdminOrderOperationResultView> confirmOrderPaid(@PathVariable String orderNo, @RequestBody(required = false) java.util.Map<String, String> req) { return ApiResponse.success(command.handleException(orderNo, new AdminOrderExceptionHandleRequest(null, null, null, null, null, null, "CONFIRM_PAID", null, null, null, null, req == null ? null : req.get("note")))); }
    @RequireAdmin @RequirePermission("order:payment-exception:handle") @Operation(summary = "人工恢复待支付") @PostMapping("/orders/{orderNo}/restore-pending-payment") public ApiResponse<AdminOrderOperationResultView> restoreOrderPendingPayment(@PathVariable String orderNo, @RequestBody(required = false) java.util.Map<String, String> req) { return ApiResponse.success(command.handleException(orderNo, new AdminOrderExceptionHandleRequest(null, null, null, null, null, null, "RESTORE_PENDING_PAYMENT", null, null, null, null, req == null ? null : req.get("note")))); }
    @RequireAdmin @RequirePermission("order:close") @Operation(summary = "人工关闭订单并释放库存") @PostMapping("/orders/{orderNo}/close-and-release-stock") public ApiResponse<AdminOrderOperationResultView> closeOrderAndReleaseStock(@PathVariable String orderNo, @RequestBody(required = false) java.util.Map<String, String> req) { return ApiResponse.success(command.handleException(orderNo, new AdminOrderExceptionHandleRequest(null, null, null, null, null, null, "CLOSE_AND_RELEASE_STOCK", null, null, null, null, req == null ? null : req.get("note")))); }

    @RequireAdmin @RequirePermission("payment:view") @Operation(summary = "查询后台支付单列表") @GetMapping("/pays") public ApiResponse<PageResult<AdminPaySummaryView>> pays(@RequestParam(required = false) String status, @RequestParam(required = false) String keyword, @RequestParam(required = false) java.time.LocalDate startDate, @RequestParam(required = false) java.time.LocalDate endDate, @RequestParam(required = false) String sortBy, @RequestParam(required = false) String sortOrder, @RequestParam(defaultValue = "1") long page, @RequestParam(defaultValue = "10") long size) { return ApiResponse.success(query.adminPays(status, keyword, startDate, endDate, page, size, sortBy, sortOrder)); }
    @RequireAdmin @RequirePermission("payment:view") @Operation(summary = "获取后台支付单详情") @GetMapping("/pays/{orderNo}") public ApiResponse<AdminPayDetailView> payDetail(@PathVariable String orderNo) { return ApiResponse.success(query.adminPayDetail(orderNo)); }
    @RequireAdmin @RequirePermission("payment:close") @Operation(summary = "后台关闭支付单") @PostMapping("/pays/{orderNo}/close") public ApiResponse<PayOrderView> closePayOrder(@PathVariable String orderNo, @Valid @RequestBody AdminClosePayOrderRequest req) { return ApiResponse.success(payManagement.closePayOrder(orderNo, req)); }
    @RequireAdmin @RequirePermission("payment:sync") @Operation(summary = "后台同步订单支付状态") @PostMapping("/pays/{orderNo}/sync-status") public ApiResponse<PayOrderView> syncPayOrderStatus(@PathVariable String orderNo) { return ApiResponse.success(payManagement.syncOrderStatus(orderNo)); }
    @RequireAdmin @RequirePermission("payment:repair") @Operation(summary = "后台补偿已成功支付订单状态") @PostMapping("/pays/{orderNo}/repair-paid") public ApiResponse<PayOrderView> repairPaidOrder(@PathVariable String orderNo) { return ApiResponse.success(payManagement.repairPaidOrder(orderNo)); }
    @RequireAdmin @RequirePermission("refund:view") @Operation(summary = "查询全局退款单列表") @GetMapping("/pays/refunds") public ApiResponse<PageResult<AdminRefundView>> globalRefunds(@RequestParam(required = false) String status, @RequestParam(required = false) String keyword, @RequestParam(required = false) java.time.LocalDate startDate, @RequestParam(required = false) java.time.LocalDate endDate, @RequestParam(defaultValue = "1") long page, @RequestParam(defaultValue = "10") long size) { return ApiResponse.success(query.adminRefundsByKeyword(status, keyword, startDate, endDate, page, size)); }
    @RequireAdmin @RequirePermission("refund:view") @Operation(summary = "查询订单退款单列表") @GetMapping("/pays/{orderNo}/refunds") public ApiResponse<PageResult<AdminRefundView>> refunds(@PathVariable String orderNo, @RequestParam(required = false) String status, @RequestParam(defaultValue = "1") long page, @RequestParam(defaultValue = "10") long size) { return ApiResponse.success(query.adminRefunds(orderNo, status, page, size)); }
    @RequireAdmin @RequirePermission("refund:sync") @Operation(summary = "后台同步退款状态") @PostMapping("/pays/{orderNo}/refunds/{refundNo}/sync-status") public ApiResponse<PayOrderView> syncRefundStatus(@PathVariable String orderNo, @PathVariable String refundNo, @RequestParam(required = false) Long refundAmountCent) { return ApiResponse.success(payManagement.reconcileRefund(orderNo, refundNo, refundAmountCent)); }
    @RequireAdmin @RequirePermission("payment:callback:view") @Operation(summary = "查询支付回调记录") @GetMapping("/pays/callback-records") public ApiResponse<PageResult<AdminPayCallbackRecordView>> payCallbackRecords(@RequestParam(required = false) String processStatus, @RequestParam(required = false) String keyword, @RequestParam(defaultValue = "1") long page, @RequestParam(defaultValue = "10") long size) { return ApiResponse.success(query.payCallbackRecords(processStatus, keyword, page, size)); }

    @RequireAdmin @RequirePermission("aftersale:view") @Operation(summary = "查询后台售后单列表") @GetMapping("/aftersales") public ApiResponse<PageResult<AdminAftersaleSummaryView>> aftersales(@RequestParam(required = false) String status, @RequestParam(required = false) String keyword, @RequestParam(required = false) Long userId, @RequestParam(defaultValue = "1") long page, @RequestParam(defaultValue = "10") long size) { return ApiResponse.success(query.adminAftersales(status, keyword, userId, page, size)); }
    @RequireAdmin @RequirePermission("aftersale:view") @Operation(summary = "获取后台售后单详情") @GetMapping("/aftersales/{aftersaleNo}") public ApiResponse<AdminAftersaleDetailView> aftersaleDetail(@PathVariable String aftersaleNo) { return ApiResponse.success(query.adminAftersaleDetail(aftersaleNo)); }
    @RequireAdmin @RequirePermission("aftersale:audit") @Operation(summary = "后台审核售后单") @PostMapping("/aftersales/{aftersaleNo}/review") public ApiResponse<AdminAftersaleDetailView> reviewAftersale(@PathVariable String aftersaleNo, @Valid @RequestBody AdminAftersaleReviewRequest req) { return ApiResponse.success(aftersaleManagement.review(aftersaleNo, req)); }

    @RequireAdmin @RequirePermission("reconciliation:view") @Operation(summary = "查询线上人工对账任务") @GetMapping("/online-reconcile-tasks") public ApiResponse<PageResult<AdminOnlineReconcileViews.TaskView>> onlineReconcileTasks(@RequestParam(required = false) String status, @RequestParam(required = false) String channel, @RequestParam(defaultValue = "1") long page, @RequestParam(defaultValue = "10") long size) { return ApiResponse.success(onlineReconciliation.tasks(status, channel, page, size)); }
    @RequireAdmin @RequirePermission("reconciliation:task:create") @Operation(summary = "创建线上人工对账任务") @PostMapping("/online-reconcile-tasks") public ApiResponse<AdminOnlineReconcileViews.TaskView> createOnlineReconcileTask(@Valid @RequestBody AdminReconcileTaskCreateRequest req) { return ApiResponse.success(onlineReconciliation.createTask(req)); }
    @RequireAdmin @RequirePermission("reconciliation:view") @Operation(summary = "获取线上人工对账任务详情") @GetMapping("/online-reconcile-tasks/{taskId}") public ApiResponse<AdminOnlineReconcileViews.TaskView> onlineReconcileTask(@PathVariable Long taskId) { return ApiResponse.success(onlineReconciliation.task(taskId)); }
    @RequireAdmin @RequirePermission("reconciliation:task:run") @Operation(summary = "生成本地账单快照") @PostMapping("/online-reconcile-tasks/{taskId}/local-bills/generate") public ApiResponse<AdminOnlineReconcileViews.TaskView> generateOnlineLocalBills(@PathVariable Long taskId) { return ApiResponse.success(onlineReconciliation.generateLocalBills(taskId)); }
    @RequireAdmin @RequirePermission("reconciliation:view") @Operation(summary = "查询本地账单快照") @GetMapping("/online-reconcile-tasks/{taskId}/local-bills") public ApiResponse<PageResult<AdminOnlineReconcileViews.LocalBillItemView>> onlineLocalBills(@PathVariable Long taskId, @RequestParam(required = false) String bizType, @RequestParam(defaultValue = "1") long page, @RequestParam(defaultValue = "10") long size) { return ApiResponse.success(onlineReconciliation.localBills(taskId, bizType, page, size)); }
    @RequireAdmin @RequirePermission("reconciliation:bill:import") @Operation(summary = "生成Mock渠道账单") @PostMapping("/online-reconcile-tasks/{taskId}/channel-bills/mock-generate") public ApiResponse<AdminOnlineReconcileViews.TaskView> generateMockChannelBills(@PathVariable Long taskId, @RequestBody(required = false) java.util.Map<String, String> req) { return ApiResponse.success(onlineReconciliation.generateMockChannelBills(taskId, req == null ? null : req.get("mode"))); }
    @RequireAdmin @RequirePermission("reconciliation:bill:import") @Operation(summary = "上传支付宝渠道账单CSV") @PostMapping("/online-reconcile-tasks/{taskId}/channel-bills/alipay-upload") public ApiResponse<AdminOnlineReconcileViews.TaskView> uploadAlipayChannelBills(@PathVariable Long taskId, @RequestPart("file") MultipartFile file) { return ApiResponse.success(onlineReconciliation.uploadAlipayChannelBills(taskId, file)); }
    @RequireAdmin @RequirePermission("reconciliation:view") @Operation(summary = "查询渠道账单快照") @GetMapping("/online-reconcile-tasks/{taskId}/channel-bills") public ApiResponse<PageResult<AdminOnlineReconcileViews.ChannelBillItemView>> onlineChannelBills(@PathVariable Long taskId, @RequestParam(required = false) String bizType, @RequestParam(defaultValue = "1") long page, @RequestParam(defaultValue = "10") long size) { return ApiResponse.success(onlineReconciliation.channelBills(taskId, bizType, page, size)); }
    @RequireAdmin @RequirePermission("reconciliation:task:run") @Operation(summary = "执行线上账单自动勾兑") @PostMapping("/online-reconcile-tasks/{taskId}/match") public ApiResponse<AdminOnlineReconcileViews.TaskView> matchOnlineReconcileTask(@PathVariable Long taskId) { return ApiResponse.success(onlineReconciliation.match(taskId)); }
    @RequireAdmin @RequirePermission("reconciliation:task:archive") @Operation(summary = "归档线上人工对账任务") @PostMapping("/online-reconcile-tasks/{taskId}/complete") public ApiResponse<AdminOnlineReconcileViews.TaskView> completeOnlineReconcileTask(@PathVariable Long taskId, @RequestBody(required = false) java.util.Map<String, String> req) { return ApiResponse.success(onlineReconciliation.completeTask(taskId, req == null ? null : req.get("remark"))); }
    @RequireAdmin @RequirePermission("reconciliation:view") @Operation(summary = "查询线上对账差异明细") @GetMapping("/online-reconcile-tasks/{taskId}/diff-items") public ApiResponse<PageResult<AdminOnlineReconcileViews.DiffItemView>> onlineDiffItems(@PathVariable Long taskId, @RequestParam(required = false) String processStatus, @RequestParam(defaultValue = "1") long page, @RequestParam(defaultValue = "10") long size) { return ApiResponse.success(onlineReconciliation.diffItems(taskId, processStatus, page, size)); }
    @RequireAdmin @RequirePermission("reconciliation:view") @Operation(summary = "查询线上对账差异详情") @GetMapping("/online-reconcile-diff-items/{diffId}") public ApiResponse<AdminOnlineReconcileViews.DiffDetailView> onlineDiffDetail(@PathVariable Long diffId) { return ApiResponse.success(onlineReconciliation.diffDetail(diffId)); }
    @RequireAdmin @RequirePermission("reconciliation:diff:handle") @Operation(summary = "处理线上对账差异") @PostMapping("/online-reconcile-diff-items/{diffId}/handle") public ApiResponse<AdminOnlineReconcileViews.DiffDetailView> handleOnlineDiff(@PathVariable Long diffId, @Valid @RequestBody AdminOnlineReconcileDiffHandleRequest req) { return ApiResponse.success(onlineReconciliation.handleDiff(diffId, req)); }
    @RequireAdmin @RequirePermission("reconciliation:view") @Operation(summary = "查询线上对账差异操作日志") @GetMapping("/online-reconcile-diff-items/{diffId}/logs") public ApiResponse<PageResult<AdminOnlineReconcileViews.OperationLogView>> onlineDiffLogs(@PathVariable Long diffId, @RequestParam(defaultValue = "1") long page, @RequestParam(defaultValue = "20") long size) { return ApiResponse.success(onlineReconciliation.diffLogs(diffId, page, size)); }
    @RequireAdmin @RequirePermission("reconciliation:view") @Operation(summary = "查询线上对账挂账跟进列表") @GetMapping("/online-reconcile-hangings") public ApiResponse<PageResult<AdminOnlineReconcileViews.HangingFollowView>> onlineHangingFollows(@RequestParam(required = false) String keyword, @RequestParam(required = false) String riskLevel, @RequestParam(defaultValue = "1") long page, @RequestParam(defaultValue = "10") long size) { return ApiResponse.success(onlineReconciliation.hangingFollows(keyword, riskLevel, page, size)); }
    @RequireAdmin @RequirePermission("reconciliation:hanging:follow") @Operation(summary = "新增线上对账挂账跟进") @PostMapping("/online-reconcile-diff-items/{diffId}/follow-up") public ApiResponse<AdminOnlineReconcileViews.DiffDetailView> followOnlineHangingDiff(@PathVariable Long diffId, @RequestBody(required = false) java.util.Map<String, String> req) { return ApiResponse.success(onlineReconciliation.followHangingDiff(diffId, req == null ? null : req.get("remark"))); }
    @RequireAdmin @RequirePermission("reconciliation:hanging:follow") @Operation(summary = "线上对账挂账转财务调账") @PostMapping("/online-reconcile-diff-items/{diffId}/transfer-finance") public ApiResponse<AdminOnlineReconcileViews.DiffDetailView> transferOnlineHangingDiffToFinance(@PathVariable Long diffId, @RequestBody(required = false) java.util.Map<String, String> req) { return ApiResponse.success(onlineReconciliation.transferHangingDiffToFinance(diffId, req == null ? null : req.get("remark"))); }
    @RequireAdmin @RequirePermission("reconciliation:hanging:follow") @Operation(summary = "线上对账挂账完结闭环") @PostMapping("/online-reconcile-diff-items/{diffId}/close-hanging") public ApiResponse<AdminOnlineReconcileViews.DiffDetailView> closeOnlineHangingDiff(@PathVariable Long diffId, @RequestBody(required = false) java.util.Map<String, String> req) { return ApiResponse.success(onlineReconciliation.closeHangingDiff(diffId, req == null ? null : req.get("remark"))); }
    @RequireAdmin @RequirePermission("reconciliation:view") @Operation(summary = "线上对账报表归档查询") @GetMapping("/online-reconcile-archive-report") public ApiResponse<AdminOnlineReconcileViews.ArchiveReportView> onlineArchiveReport(@RequestParam(required = false) java.time.LocalDate startDate, @RequestParam(required = false) java.time.LocalDate endDate, @RequestParam(required = false) String channel, @RequestParam(required = false) String bizType, @RequestParam(required = false) String diffType) { return ApiResponse.success(onlineReconciliation.archiveReport(startDate, endDate, channel, bizType, diffType)); }
    @RequireAdmin @RequirePermission("reconciliation:view") @Operation(summary = "查询线上对账任务操作日志") @GetMapping("/online-reconcile-tasks/{taskId}/logs") public ApiResponse<PageResult<AdminOnlineReconcileViews.OperationLogView>> onlineTaskLogs(@PathVariable Long taskId, @RequestParam(defaultValue = "1") long page, @RequestParam(defaultValue = "20") long size) { return ApiResponse.success(onlineReconciliation.taskOperationLogs(taskId, page, size)); }

    @RequireAdmin @RequirePermission("reconciliation:view") @Operation(summary = "查询后台对账一期增强概览") @GetMapping("/reconciliations/overview") public ApiResponse<AdminReconciliationOverviewView> reconciliationOverview() { return ApiResponse.success(query.reconciliationOverview()); }
    @RequireAdmin @RequirePermission("reconciliation:view") @Operation(summary = "查询后台对账列表") @GetMapping("/reconciliations") public ApiResponse<PageResult<AdminReconcileRowView>> reconciliations(@RequestParam(required = false) String status, @RequestParam(required = false) String sortBy, @RequestParam(required = false) String sortOrder, @RequestParam(defaultValue = "1") long page, @RequestParam(defaultValue = "10") long size) { return ApiResponse.success(query.reconcileList(status, page, size, sortBy, sortOrder)); }
    @RequireAdmin @RequirePermission("reconciliation:task:run") @Operation(summary = "执行单笔对账") @PostMapping("/reconciliations/{orderNo}/run") public ApiResponse<AdminReconcileRowView> runReconcile(@PathVariable String orderNo) { return ApiResponse.success(payManagement.reconcile(orderNo)); }
    @RequireAdmin @RequirePermission("reconciliation:diff:handle") @Operation(summary = "处理对账异常") @PostMapping("/reconciliations/{orderNo}/handle") public ApiResponse<AdminReconcileRowView> handleReconcile(@PathVariable String orderNo, @Valid @RequestBody AdminReconcileHandleRequest req) { return ApiResponse.success(payManagement.handleReconcile(orderNo, req)); }
    @RequireAdmin @RequirePermission("reconciliation:view") @Operation(summary = "查询支付/退款对账记录") @GetMapping("/reconciliations/pay-records") public ApiResponse<PageResult<AdminPayReconciliationRecordView>> payReconciliationRecords(@RequestParam(required = false) String bizType, @RequestParam(required = false) String status, @RequestParam(required = false) String repairStatus, @RequestParam(required = false) String keyword, @RequestParam(defaultValue = "1") long page, @RequestParam(defaultValue = "10") long size) { return ApiResponse.success(query.payReconciliationRecords(bizType, status, repairStatus, keyword, page, size)); }
    @RequireAdmin @RequirePermission("reconciliation:view") @Operation(summary = "获取支付/退款对账记录详情") @GetMapping("/reconciliations/pay-records/{id}") public ApiResponse<AdminPayReconciliationRecordView> payReconciliationRecord(@PathVariable Long id) { return ApiResponse.success(query.payReconciliationRecord(id)); }
    @RequireAdmin @RequirePermission("reconciliation:diff:repair") @Operation(summary = "执行业务化支付/退款对账处置") @PostMapping("/reconciliations/pay-records/{id}/handle") public ApiResponse<AdminReconciliationHandleResultView> handlePayReconciliationRecord(@PathVariable Long id, @Valid @RequestBody AdminReconcileHandleRequest req) { return ApiResponse.success(payManagement.handlePayReconciliationRecord(id, req)); }
    @RequireAdmin @RequirePermission("reconciliation:diff:handle") @Operation(summary = "标记支付/退款对账记录已处理") @PostMapping("/reconciliations/pay-records/{id}/done") public ApiResponse<AdminPayReconciliationRecordView> donePayReconciliationRecord(@PathVariable Long id, @RequestBody(required = false) java.util.Map<String, String> req) { return ApiResponse.success(query.donePayReconciliationRecord(id, req == null ? null : req.get("remark"))); }
    @RequireAdmin @RequirePermission("reconciliation:diff:handle") @Operation(summary = "忽略支付/退款对账记录") @PostMapping("/reconciliations/pay-records/{id}/ignore") public ApiResponse<AdminPayReconciliationRecordView> ignorePayReconciliationRecord(@PathVariable Long id, @RequestBody(required = false) java.util.Map<String, String> req) { return ApiResponse.success(query.ignorePayReconciliationRecord(id, req == null ? null : req.get("remark"))); }
    @RequireAdmin @RequirePermission("stock:reconcile:view") @Operation(summary = "查询库存对账列表") @GetMapping("/reconciliations/stocks") public ApiResponse<PageResult<com.mallfei.stock.application.vo.StockReconciliationRecordView>> stockReconciliations(@RequestParam(required = false) Long skuId, @RequestParam(required = false) String status, @RequestParam(required = false) String sortBy, @RequestParam(required = false) String sortOrder, @RequestParam(defaultValue = "1") long page, @RequestParam(defaultValue = "10") long size) { return ApiResponse.success(stock.reconciliationRecords(skuId, status, page, size, sortBy, sortOrder)); }
    @RequireAdmin @RequirePermission("stock:reconcile:view") @Operation(summary = "获取库存对账详情") @GetMapping("/reconciliations/stocks/{id}") public ApiResponse<com.mallfei.stock.application.vo.StockReconciliationRecordView> stockReconciliationDetail(@PathVariable Long id) { return ApiResponse.success(stock.reconciliationRecord(id)); }
    @RequireAdmin @RequirePermission("stock:reconcile:repair") @Operation(summary = "修复库存对账差异") @PostMapping("/reconciliations/stocks/{id}/repair") public ApiResponse<com.mallfei.stock.application.vo.StockReconciliationRecordView> repairStockReconciliation(@PathVariable Long id, @RequestBody(required = false) java.util.Map<String, String> req) { return ApiResponse.success(stock.repairReconciliationRecord(id, req == null ? null : req.get("remark"))); }
    @RequireAdmin @RequirePermission("stock:reconcile:repair") @Operation(summary = "忽略库存对账差异") @PostMapping("/reconciliations/stocks/{id}/ignore") public ApiResponse<com.mallfei.stock.application.vo.StockReconciliationRecordView> ignoreStockReconciliation(@PathVariable Long id, @RequestBody(required = false) java.util.Map<String, String> req) { return ApiResponse.success(stock.ignoreReconciliationRecord(id, req == null ? null : req.get("remark"))); }

    @RequireAdmin @RequirePermission("stock:view") @Operation(summary = "查询后台库存列表") @GetMapping("/stocks") public ApiResponse<PageResult<StockSnapshot>> stocks(@RequestParam(required = false) Long skuId, @RequestParam(required = false) String stockStatus, @RequestParam(required = false) String warningStatus, @RequestParam(required = false) String sortBy, @RequestParam(required = false) String sortOrder, @RequestParam(defaultValue = "1") long page, @RequestParam(defaultValue = "20") long size) { return ApiResponse.success(query.stockList(skuId, stockStatus, warningStatus, page, size, sortBy, sortOrder)); }
    @RequireAdmin @RequirePermission("stock:view") @Operation(summary = "查询当前时间戳近3日有库存日志的SKU库存列表") @GetMapping("/stocks/today-active") public ApiResponse<PageResult<AdminTodayActiveStockView>> todayActiveStocks(@RequestParam(required = false) Long skuId, @RequestParam(required = false) String stockStatus, @RequestParam(required = false) String warningStatus, @RequestParam(required = false) java.time.LocalDate stockDate, @RequestParam(required = false) Long currentTimestamp, @RequestParam(required = false) String sortBy, @RequestParam(required = false) String sortOrder, @RequestParam(defaultValue = "1") long page, @RequestParam(defaultValue = "20") long size) { return ApiResponse.success(query.todayActiveStockList(skuId, stockStatus, warningStatus, stockDate, currentTimestamp, page, size, sortBy, sortOrder)); }
    @RequireAdmin @RequirePermission("stock:warning:view") @Operation(summary = "查询库存预警列表") @GetMapping("/stocks/warnings") public ApiResponse<PageResult<StockSnapshot>> warningStocks(@RequestParam(defaultValue = "1") long page, @RequestParam(defaultValue = "20") long size) { return ApiResponse.success(query.warningStocks(page, size)); }
    @RequireAdmin @RequirePermission("stock:log:view") @Operation(summary = "查询库存操作日志") @GetMapping("/stocks/logs") public ApiResponse<PageResult<AdminStockOperationLogView>> stockLogs(@RequestParam(required = false) Long skuId, @RequestParam(required = false) String operationType, @RequestParam(required = false) String startTime, @RequestParam(required = false) String endTime, @RequestParam(required = false) String sortBy, @RequestParam(required = false) String sortOrder, @RequestParam(defaultValue = "1") long page, @RequestParam(defaultValue = "20") long size) { return ApiResponse.success(query.stockLogs(skuId, operationType, startTime, endTime, page, size, sortBy, sortOrder)); }
    @RequireAdmin @RequirePermission("stock:policy:update") @Operation(summary = "后台调整库存策略") @PutMapping("/stocks/{skuId}/policy") public ApiResponse<StockSnapshot> updateStockPolicy(@PathVariable Long skuId, @Valid @RequestBody AdminStockPolicyUpdateRequest req) { return ApiResponse.success(stock.updatePolicy(skuId, req)); }
    @RequireAdmin @RequirePermission("stock:adjust") @Operation(summary = "后台手工调整库存") @PutMapping("/stocks/{skuId}/adjust") public ApiResponse<StockSnapshot> adjustStock(@PathVariable Long skuId, @Valid @RequestBody AdminStockAdjustRequest req) { return ApiResponse.success(stock.adjust(skuId, req)); }
    @RequireAdmin @RequirePermission("stock:warning:handle") @Operation(summary = "后台处理库存预警") @PostMapping("/stocks/{skuId}/warning-handle") public ApiResponse<StockSnapshot> handleStockWarning(@PathVariable Long skuId, @Valid @RequestBody AdminStockWarningHandleRequest req) { return ApiResponse.success(stock.handleWarning(skuId, req)); }
    @RequireAdmin @RequirePermission("stock:reconcile:check") @Operation(summary = "发起库存一致性校验") @PostMapping("/stocks/{skuId}/consistency-check") public ApiResponse<StockConsistencyCheckView> checkStockConsistency(@PathVariable Long skuId) { return ApiResponse.success(stock.checkConsistency(skuId)); }

    @RequireAdmin @RequirePermission("product:view") @Operation(summary = "获取后台类目列表") @GetMapping("/categories") public ApiResponse<java.util.List<CategoryAdminView>> categories() { return ApiResponse.success(product.adminCategories()); }
    @RequireAdmin @RequirePermission("category:manage") @Operation(summary = "新增类目") @PostMapping("/categories") public ApiResponse<Category> createCategory(@Valid @RequestBody AdminCreateCategoryRequest req) { return ApiResponse.success(product.createCategory(req.name(), req.parentId(), req.sortOrder())); }
    @RequireAdmin @RequirePermission("category:manage") @Operation(summary = "修改类目") @PutMapping("/categories/{categoryId}") public ApiResponse<Category> updateCategory(@PathVariable Long categoryId, @Valid @RequestBody AdminUpdateCategoryRequest req) { return ApiResponse.success(product.updateCategory(categoryId, req.name(), req.parentId(), req.sortOrder(), req.status())); }
    @RequireAdmin @RequirePermission("product:sales-threshold:view") @Operation(summary = "查询商品销售表现默认阈值") @GetMapping("/products/sales-threshold-config") public ApiResponse<AdminProductSalesThresholdConfigView> productSalesThresholdConfig() { return ApiResponse.success(operationConfig.productSalesThresholdConfig()); }
    @RequireAdmin @RequirePermission("product:sales-threshold:config") @Operation(summary = "修改商品销售表现默认阈值") @PutMapping("/products/sales-threshold-config") public ApiResponse<AdminProductSalesThresholdConfigView> updateProductSalesThresholdConfig(@Valid @RequestBody AdminProductSalesThresholdConfigRequest req) { return ApiResponse.success(operationConfig.updateProductSalesThresholdConfig(req)); }
    @RequireAdmin @RequirePermission("product:view") @Operation(summary = "查询后台商品列表") @GetMapping("/products") public ApiResponse<PageResponse<AdminProductPageRowView>> productPage(@RequestParam(required = false) String keyword, @RequestParam(required = false) Long categoryId, @RequestParam(required = false) String status, @RequestParam(required = false) String salesBand, @RequestParam(required = false) String stockWarningStatus, @RequestParam(required = false) Integer hotSalesThreshold, @RequestParam(required = false) Integer lowSalesThreshold, @RequestParam(required = false) String sortBy, @RequestParam(required = false) String sortOrder, @RequestParam(defaultValue = "1") long page, @RequestParam(defaultValue = "10") long size) { return ApiResponse.success(product.adminProductPage(new AdminProductPageQuery(keyword, categoryId, status, salesBand, stockWarningStatus, hotSalesThreshold, lowSalesThreshold, sortBy, sortOrder, page, size))); }
    @RequireAdmin @RequirePermission("product:view") @Operation(summary = "获取后台商品详情") @GetMapping("/products/{productId}") public ApiResponse<AdminProductDetailView> productDetail(@PathVariable Long productId) { return ApiResponse.success(product.adminProductDetail(productId)); }
    @RequireAdmin @RequirePermission("product:create") @Operation(summary = "新增商品") @PostMapping("/products") public ApiResponse<AdminProductSummaryView> createProduct(@Valid @RequestBody AdminCreateProductRequest req) { return ApiResponse.success(product.createProduct(req)); }
    @RequireAdmin @RequirePermission("product:update") @Operation(summary = "修改商品") @PutMapping("/products/{productId}") public ApiResponse<AdminProductSummaryView> updateProduct(@PathVariable Long productId, @Valid @RequestBody AdminUpdateProductRequest req) { return ApiResponse.success(product.updateProduct(productId, req)); }
    @RequireAdmin @RequirePermission("product:status:update") @Operation(summary = "修改商品状态") @PatchMapping("/products/{productId}/status") public ApiResponse<AdminProductSummaryView> updateProductStatus(@PathVariable Long productId, @Valid @RequestBody AdminProductStatusOperateRequest req) { return ApiResponse.success(productManagement.updateStatus(productId, req)); }
    @RequireAdmin @RequirePermission("product:violation:handle") @Operation(summary = "处理商品运营事件") @PostMapping("/products/{productId}/violation-handle") public ApiResponse<AdminProductSummaryView> handleProductViolation(@PathVariable Long productId, @Valid @RequestBody AdminProductViolationHandleRequest req) { return ApiResponse.success(productManagement.handleViolation(productId, req)); }

    public record AdminCreateCategoryRequest(@NotBlank(message = "类目名称不能为空") String name, Long parentId, Integer sortOrder) {}
    public record AdminUpdateCategoryRequest(@NotBlank(message = "类目名称不能为空") String name, Long parentId, Integer sortOrder, @NotBlank(message = "类目状态不能为空") String status) {}
}