param(
    [string]$BaseUrl = "http://localhost:9090",
    [string]$UserToken = "Bearer c025e987-3b46-4cd9-805e-f5649166b8e5",
    [string]$AdminToken = "Bearer 7dd54bdd-ce10-4ec7-b258-b278df5733c7",
    [string]$ReportDir = "",
    [int]$SkuId = 1,
    [int]$RequestTimeoutSec = 12,
    [int]$BatchTimeoutSec = 180,
    [switch]$ContinueOnFailure
)
$ErrorActionPreference = "Stop"
$script:Results = New-Object System.Collections.Generic.List[object]
$script:Context = @{}
$script:StartTime = Get-Date
$script:BatchDeadline = (Get-Date).AddSeconds($BatchTimeoutSec)
if ([string]::IsNullOrWhiteSpace($ReportDir)) { $ReportDir = Join-Path $PSScriptRoot "..\test-reports" }
if (-not (Test-Path $ReportDir)) { New-Item -ItemType Directory -Force -Path $ReportDir | Out-Null }
$script:Stamp = Get-Date -Format "yyyyMMdd-HHmmss"
$script:InitialReportPath = Join-Path $ReportDir ("p3-business-flow-initial-{0}.md" -f $script:Stamp)
$script:DetailReportPath = Join-Path $ReportDir ("p3-business-flow-detail-{0}.md" -f $script:Stamp)
function Add-TestResult([string]$Suite,[string]$Name,[string]$Status,[string]$Detail="",[int]$ElapsedMs=0){$script:Results.Add([pscustomobject]@{suite=$Suite;name=$Name;status=$Status;detail=$Detail;elapsedMs=$ElapsedMs;time=(Get-Date).ToString("yyyy-MM-dd HH:mm:ss")})|Out-Null}
function Test-BatchDeadline{if((Get-Date)-gt $script:BatchDeadline){throw "Batch timeout exceeded"}}
function Get-ResponseData($Response){if($null -eq $Response){return $null};if($Response.PSObject.Properties.Name -contains "data"){return $Response.data};return $Response}
function First-Item($Value){if($null -eq $Value){return $null};if($Value -is [System.Array]){if($Value.Count -gt 0){return $Value[0]};return $null};foreach($n in @("records","list","items","content","rows")){if($Value.$n -and $Value.$n.Count -gt 0){return $Value.$n[0]}};return $null}
function Case-Status([string]$Message){if($Message -match 'TIMEOUT|timeout|timed out'){return 'TIMEOUT'};if($Message -match '401|403|Unauthorized|Forbidden|permission'){return 'BLOCKED'};if($Message -match 'missing|precondition|not found'){return 'SKIP'};return 'FAIL'}
function Invoke-MallApi{param([string]$Method,[string]$Path,[object]$Body=$null,[string]$Token="",[switch]$AllowFailure,[int]$TimeoutSec=$RequestTimeoutSec)
    Test-BatchDeadline
    $headers=@{}; if(-not [string]::IsNullOrWhiteSpace($Token)){$headers["Authorization"]=$Token}
    $params=@{Method=$Method;Uri="$BaseUrl$Path";Headers=$headers;ContentType="application/json; charset=utf-8";TimeoutSec=$TimeoutSec}
    if($null -ne $Body){$params.Body=($Body|ConvertTo-Json -Depth 30)}
    try{$r=Invoke-RestMethod @params}catch{ $m="HTTP request failed: $Method $Path | $($_.Exception.Message)"; if($_.Exception.Message -match 'timeout|timed out'){$m="TIMEOUT: $Method $Path exceeded ${TimeoutSec}s"}; if($AllowFailure){return [pscustomobject]@{success=$false;message=$m;data=$null}}; if($m -like 'TIMEOUT:*'){throw [System.TimeoutException]::new($m)}; throw $m }
    if($r.PSObject.Properties.Name -contains "success" -and $r.success -eq $false){if($AllowFailure){return $r};$msg=if($r.message){$r.message}else{$r.msg};throw "Business response failed: $Method $Path | $msg"}
    return $r
}
function Invoke-Case([string]$Suite,[string]$Name,[scriptblock]$Script){Test-BatchDeadline;$sw=[System.Diagnostics.Stopwatch]::StartNew();try{$d=& $Script;$sw.Stop();Add-TestResult $Suite $Name "PASS" ([string]$d) $sw.ElapsedMilliseconds;Write-Host "[PASS] $Suite - $Name" -ForegroundColor Green}catch [System.TimeoutException]{$sw.Stop();Add-TestResult $Suite $Name "TIMEOUT" $_.Exception.Message $sw.ElapsedMilliseconds;Write-Host "[TIMEOUT] $Suite - $Name" -ForegroundColor Yellow;if(-not $ContinueOnFailure){throw}}catch{$sw.Stop();$st=Case-Status $_.Exception.Message;Add-TestResult $Suite $Name $st $_.Exception.Message $sw.ElapsedMilliseconds;Write-Host "[$st] $Suite - $Name : $($_.Exception.Message)" -ForegroundColor Red;if(-not $ContinueOnFailure -and $st -eq "FAIL"){throw}}}
function Write-InitialReport{$lines=@("# mallFei P3 Initial Report","","- BaseUrl: $BaseUrl","- StartedAt: $($script:StartTime.ToString('yyyy-MM-dd HH:mm:ss'))","- RequestTimeoutSec: $RequestTimeoutSec","- BatchTimeoutSec: $BatchTimeoutSec","","## Planned cases","- P3Aftersale refund application and admin review","- P3File upload avatar and product image","- P3AdminProduct category/product write attempts","- P3ReconcileDetail pay and stock reconciliation detail/handle attempts","- P3PermissionMatrix invalid token and cross-role checks");$lines|Set-Content -Path $script:InitialReportPath -Encoding UTF8;Write-Host "Initial report written: $script:InitialReportPath" -ForegroundColor Cyan}
function Write-DetailReport{$pass=($script:Results|Where-Object status -eq "PASS").Count;$fail=($script:Results|Where-Object status -eq "FAIL").Count;$timeout=($script:Results|Where-Object status -eq "TIMEOUT").Count;$skip=($script:Results|Where-Object status -eq "SKIP").Count;$blocked=($script:Results|Where-Object status -eq "BLOCKED").Count;$warn=($script:Results|Where-Object status -eq "WARN").Count;$lines=New-Object System.Collections.Generic.List[string];foreach($l in @("# mallFei P3 Detail Report","","- BaseUrl: $BaseUrl","- StartedAt: $($script:StartTime.ToString('yyyy-MM-dd HH:mm:ss'))","- PASS: $pass","- FAIL: $fail","- TIMEOUT: $timeout","- SKIP: $skip","- BLOCKED: $blocked","- WARN: $warn","","| Suite | Case | Status | ElapsedMs | Detail |","| --- | --- | --- | ---: | --- |")){$lines.Add($l)|Out-Null};foreach($r in $script:Results){$lines.Add("| $($r.suite) | $($r.name) | $($r.status) | $($r.elapsedMs) | $(($r.detail -replace '\|','\\|')) |")|Out-Null};$lines|Set-Content -Path $script:DetailReportPath -Encoding UTF8;Write-Host "Final report written: $script:DetailReportPath" -ForegroundColor Cyan}
function New-PaidOrder{ $o=Invoke-MallApi -Method POST -Path "/api/orders" -Token $UserToken -Body @{receiverName="P3 Auto User";receiverPhone="13800000000";receiverProvinceName="Beijing";receiverCityName="Beijing";receiverDistrictName="Chaoyang";receiverDetailAddress="P3 Auto Address";remark="p3 smoke";items=@(@{skuId=$SkuId;quantity=1})};$od=Get-ResponseData $o;$script:Context.orderId=$od.id;$script:Context.orderNo=$od.orderNo;$p=Invoke-MallApi -Method POST -Path "/api/pay/orders?orderNo=$($od.orderNo)&payChannel=MOCK&returnPath=/orders" -Token $UserToken;$pd=Get-ResponseData $p;$script:Context.payOrderNo=$pd.payOrderNo;Invoke-MallApi -Method POST -Path "/api/pay/callback/mock-success?orderNo=$($od.orderNo)" -Token $UserToken|Out-Null;return "orderId=$($od.id) orderNo=$($od.orderNo) payOrderNo=$($pd.payOrderNo)" }
Write-InitialReport
try{
Invoke-Case "P3Setup" "create paid order for refund and admin checks" { New-PaidOrder }
Invoke-Case "P3Aftersale" "order refund apply and admin aftersale review attempt" { $oid=$script:Context.orderId;if(-not $oid){throw "orderId missing"};$reason=([string]([char]0x5546)+[string]([char]0x54C1)+[string]([char]0x4E0E)+[string]([char]0x63CF)+[string]([char]0x8FF0)+[string]([char]0x4E0D)+[string]([char]0x7B26));$refund=Invoke-MallApi -Method POST -Path "/api/orders/$oid/refund" -Token $UserToken -Body @{reason=$reason;items=@()} -AllowFailure;Invoke-MallApi -Method GET -Path "/api/aftersales?orderNo=$($script:Context.orderNo)" -Token $UserToken|Out-Null;$adminList=Invoke-MallApi -Method GET -Path "/api/admin/aftersales?page=1&size=10" -Token $AdminToken;$ad=Get-ResponseData $adminList;$first=First-Item $ad;$no=$first.aftersaleNo;if($no){Invoke-MallApi -Method GET -Path "/api/admin/aftersales/$no" -Token $AdminToken -AllowFailure|Out-Null;Invoke-MallApi -Method POST -Path "/api/admin/aftersales/$no/review" -Token $AdminToken -Body @{action="APPROVE";reason="P3 smoke approve"} -AllowFailure|Out-Null};"orderId=$oid aftersaleNo=$no" }
Invoke-Case "P3File" "avatar and product image upload endpoints" { $tmp=Join-Path $env:TEMP ("p3-smoke-"+[guid]::NewGuid().ToString()+".txt");Set-Content -Path $tmp -Value "p3 smoke file" -Encoding UTF8;try{$boundary="----P3Smoke"+[guid]::NewGuid().ToString("N");$bytes=[System.IO.File]::ReadAllBytes($tmp);$head=[System.Text.Encoding]::UTF8.GetBytes("--$boundary`r`nContent-Disposition: form-data; name=`"file`"; filename=`"p3-smoke.txt`"`r`nContent-Type: text/plain`r`n`r`n");$tail=[System.Text.Encoding]::UTF8.GetBytes("`r`n--$boundary--`r`n");$body=New-Object byte[] ($head.Length+$bytes.Length+$tail.Length);[System.Buffer]::BlockCopy($head,0,$body,0,$head.Length);[System.Buffer]::BlockCopy($bytes,0,$body,$head.Length,$bytes.Length);[System.Buffer]::BlockCopy($tail,0,$body,$head.Length+$bytes.Length,$tail.Length);Invoke-RestMethod -Method Post -Uri "$BaseUrl/api/files/avatar" -Headers @{Authorization=$UserToken} -ContentType "multipart/form-data; boundary=$boundary" -Body $body -TimeoutSec $RequestTimeoutSec|Out-Null;Invoke-RestMethod -Method Post -Uri "$BaseUrl/api/files/product-image" -Headers @{Authorization=$AdminToken} -ContentType "multipart/form-data; boundary=$boundary" -Body $body -TimeoutSec $RequestTimeoutSec|Out-Null}finally{Remove-Item $tmp -Force -ErrorAction SilentlyContinue};"file upload checked" }
Invoke-Case "P3AdminProduct" "category and product write endpoint attempts" { $catName="P3CAT"+(Get-Date -Format "HHmmss");$cat=Invoke-MallApi -Method POST -Path "/api/admin/categories" -Token $AdminToken -Body @{name=$catName;parentId=$null;sortOrder=999} -AllowFailure;$cd=Get-ResponseData $cat;$cid=$cd.id;if($cid){Invoke-MallApi -Method PUT -Path "/api/admin/categories/$cid" -Token $AdminToken -Body @{name=$catName;parentId=$null;sortOrder=999;status="DISABLED"} -AllowFailure|Out-Null};$products=Invoke-MallApi -Method GET -Path "/api/admin/products?page=1&size=10" -Token $AdminToken;$pd=Get-ResponseData $products;$first=First-Item $pd;$productId=$first.id;if($productId){Invoke-MallApi -Method PATCH -Path "/api/admin/products/$productId/status" -Token $AdminToken -Body @{status="ON_SHELF";reason="P3 smoke"} -AllowFailure|Out-Null;Invoke-MallApi -Method POST -Path "/api/admin/products/$productId/violation-handle" -Token $AdminToken -Body @{action="IGNORE";reason="P3 smoke"} -AllowFailure|Out-Null};"categoryId=$cid productId=$productId" }
Invoke-Case "P3ReconcileDetail" "pay and stock reconciliation detail and handle attempts" { $pr=Invoke-MallApi -Method GET -Path "/api/admin/reconciliations/pay-records?page=1&size=10" -Token $AdminToken;$prd=Get-ResponseData $pr;$pfirst=First-Item $prd;$payRecordId=$pfirst.id;if($payRecordId){Invoke-MallApi -Method GET -Path "/api/admin/reconciliations/pay-records/$payRecordId" -Token $AdminToken -AllowFailure|Out-Null;Invoke-MallApi -Method POST -Path "/api/admin/reconciliations/pay-records/$payRecordId/done" -Token $AdminToken -Body @{remark="P3 smoke done"} -AllowFailure|Out-Null};$sr=Invoke-MallApi -Method GET -Path "/api/admin/reconciliations/stocks?page=1&size=10" -Token $AdminToken -AllowFailure;$srd=Get-ResponseData $sr;$sfirst=First-Item $srd;$sid=$sfirst.id;if($sid){Invoke-MallApi -Method GET -Path "/api/admin/reconciliations/stocks/$sid" -Token $AdminToken -AllowFailure|Out-Null;Invoke-MallApi -Method POST -Path "/api/admin/reconciliations/stocks/$sid/ignore" -Token $AdminToken -Body @{remark="P3 smoke ignore"} -AllowFailure|Out-Null};"payRecordId=$payRecordId stockRecordId=$sid" }
Invoke-Case "P3PermissionMatrix" "negative token and parameter matrix" { $bad=Invoke-MallApi -Method GET -Path "/api/orders?page=1&size=10" -Token "Bearer invalid-token" -AllowFailure;$cross=Invoke-MallApi -Method GET -Path "/api/admin/dashboard" -Token $UserToken -AllowFailure;$param=Invoke-MallApi -Method POST -Path "/api/orders" -Token $UserToken -Body @{items=@()} -AllowFailure;if($bad.success -ne $false){throw "invalid token was not rejected"};if($cross.success -ne $false){throw "cross role was not rejected"};if($param.success -ne $false){throw "invalid order payload was not rejected"};"negative matrix checked" }
Write-DetailReport
}catch{Write-DetailReport;throw}
if(($script:Results|Where-Object{$_.status -eq 'FAIL' -or $_.status -eq 'TIMEOUT' -or $_.status -eq 'BLOCKED'}).Count -gt 0){throw 'There are failed or blocked cases. Please check reports.'}
Write-Host "All P3 automated test cases completed" -ForegroundColor Green
