param(
[string]$BaseUrl="http://localhost:9090",
[string]$UserToken="Bearer c025e987-3b46-4cd9-805e-f5649166b8e5",
[string]$AdminToken="Bearer 7dd54bdd-ce10-4ec7-b258-b278df5733c7",
[string]$ReportDir="",
[int]$SkuId=1,
[int]$RequestTimeoutSec=12,
[int]$BatchTimeoutSec=180,
[switch]$ContinueOnFailure
)
$ErrorActionPreference="Stop"
$script:Results=New-Object System.Collections.Generic.List[object]
$script:Context=@{}
$script:StartTime=Get-Date
$script:BatchDeadline=(Get-Date).AddSeconds($BatchTimeoutSec)
if([string]::IsNullOrWhiteSpace($ReportDir)){$ReportDir=Join-Path $PSScriptRoot "..\test-reports"}
if(-not(Test-Path $ReportDir)){New-Item -ItemType Directory -Force -Path $ReportDir|Out-Null}
$script:Stamp=Get-Date -Format "yyyyMMdd-HHmmss"
$script:InitialReportPath=Join-Path $ReportDir ("p4-business-flow-initial-{0}.md" -f $script:Stamp)
$script:DetailReportPath=Join-Path $ReportDir ("p4-business-flow-detail-{0}.md" -f $script:Stamp)
function Add-Result($s,$n,$st,$d,$ms){$script:Results.Add([pscustomobject]@{suite=$s;name=$n;status=$st;detail=$d;elapsedMs=$ms})|Out-Null}
function Deadline{if((Get-Date)-gt $script:BatchDeadline){throw "Batch timeout"}}
function GetRespData($r){if($null -eq $r){return $null};if($r.PSObject.Properties.Name -contains "data"){return $r.data};return $r}
function First($v){if($null -eq $v){return $null};if($v -is [System.Array]){if($v.Count -gt 0){return $v[0]};return $null};foreach($n in @("records","list","items","content","rows")){if($v.$n -and $v.$n.Count -gt 0){return $v.$n[0]}};return $null}
function StatusOf($m){if($m -match 'timeout|TIMEOUT'){return 'TIMEOUT'};if($m -match '401|403|Unauthorized|Forbidden|permission'){return 'BLOCKED'};if($m -match 'missing|not found'){return 'SKIP'};return 'FAIL'}
function Api{param($Method,$Path,$Body=$null,$Token="",[switch]$AllowFailure)
Deadline;$h=@{};if($Token){$h.Authorization=$Token};$p=@{Method=$Method;Uri="$BaseUrl$Path";Headers=$h;ContentType="application/json; charset=utf-8";TimeoutSec=$RequestTimeoutSec};if($null -ne $Body){$p.Body=($Body|ConvertTo-Json -Depth 30)}
try{$r=Invoke-RestMethod @p}catch{$m="HTTP request failed: $Method $Path | $($_.Exception.Message)";if($_.Exception.Message -match 'timeout|timed out'){$m="TIMEOUT: $Method $Path"};if($AllowFailure){return [pscustomobject]@{success=$false;message=$m;data=$null}};throw $m}
if($r.PSObject.Properties.Name -contains "success" -and $r.success -eq $false){if($AllowFailure){return $r};throw "Business failed: $Method $Path | $($r.message)"};return $r}
function Case($s,$n,[scriptblock]$b){$sw=[Diagnostics.Stopwatch]::StartNew();try{$d=& $b;$sw.Stop();Add-Result $s $n "PASS" ([string]$d) $sw.ElapsedMilliseconds;Write-Host "[PASS] $s - $n" -ForegroundColor Green}catch{$sw.Stop();$st=StatusOf $_.Exception.Message;Add-Result $s $n $st $_.Exception.Message $sw.ElapsedMilliseconds;Write-Host "[$st] $s - $n : $($_.Exception.Message)" -ForegroundColor Red;if(-not $ContinueOnFailure -and $st -eq 'FAIL'){throw}}}
function Reports{$lines=@("# P4 Initial Report","BaseUrl: $BaseUrl","StartedAt: $($script:StartTime)","Cases: product full, account permission, refund reconcile, upload negative, permission deep");$lines|Set-Content $script:InitialReportPath -Encoding UTF8;$pass=($script:Results|? status -eq PASS).Count;$fail=($script:Results|? status -eq FAIL).Count;$tout=($script:Results|? status -eq TIMEOUT).Count;$skip=($script:Results|? status -eq SKIP).Count;$blocked=($script:Results|? status -eq BLOCKED).Count;$out=New-Object System.Collections.Generic.List[string];foreach($l in @("# P4 Detail Report","PASS=$pass FAIL=$fail TIMEOUT=$tout SKIP=$skip BLOCKED=$blocked","","| Suite | Case | Status | ElapsedMs | Detail |","| --- | --- | --- | ---: | --- |")){$out.Add($l)|Out-Null};foreach($r in $script:Results){$out.Add("| $($r.suite) | $($r.name) | $($r.status) | $($r.elapsedMs) | $(($r.detail -replace '\|','\\|')) |")|Out-Null};$out|Set-Content $script:DetailReportPath -Encoding UTF8;Write-Host "Initial report written: $script:InitialReportPath";Write-Host "Final report written: $script:DetailReportPath"}
function PaidOrder{$o=Api POST "/api/orders" @{receiverName="P4 User";receiverPhone="13800000000";receiverProvinceName="Beijing";receiverCityName="Beijing";receiverDistrictName="Chaoyang";receiverDetailAddress="P4 Address";remark="p4";items=@(@{skuId=$SkuId;quantity=1})} $UserToken;$od=GetRespData $o;$script:Context.orderId=$od.id;$script:Context.orderNo=$od.orderNo;$p=Api POST "/api/pay/orders?orderNo=$($od.orderNo)&payChannel=MOCK&returnPath=/orders" $null $UserToken;$pd=GetRespData $p;$script:Context.payOrderNo=$pd.payOrderNo;Api POST "/api/pay/callback/mock-success?orderNo=$($od.orderNo)" $null $UserToken|Out-Null;"orderId=$($od.id) orderNo=$($od.orderNo) payOrderNo=$($pd.payOrderNo)"}
try{
Case "P4Setup" "create paid order" {PaidOrder}
Case "P4ProductFull" "admin product create update status" {$cat=Api GET "/api/admin/categories" $null $AdminToken;$fc=First (GetRespData $cat);$categoryId=if($fc.id){$fc.id}else{1};$stamp=Get-Date -Format HHmmss;$sku="P4-SKU-$stamp";$cr=Api POST "/api/admin/products" @{name="P4Product$stamp";categoryId=$categoryId;mainImageUrl="https://example.com/p4.png";description="p4";skus=@(@{skuCode=$sku;skuName="P4Sku";specJson="{}";salePriceCent=1999;originPriceCent=2999;initialStock=3})} $AdminToken;$prod=GetRespData $cr;$productId=if($prod.id){$prod.id}else{$prod.productId};if(-not $productId){throw "productId missing"};Api GET "/api/admin/products/$productId" $null $AdminToken|Out-Null;Api PATCH "/api/admin/products/$productId/status" @{status="ONLINE";reason="P4 online"} $AdminToken -AllowFailure|Out-Null;Api PATCH "/api/admin/products/$productId/status" @{status="OFFLINE";reason="P4 offline"} $AdminToken -AllowFailure|Out-Null;"productId=$productId categoryId=$categoryId"}
Case "P4AccountPermission" "admin account role permission enable disable" {$roles=Api GET "/api/admin/roles" $null $AdminToken;$role=First (GetRespData $roles);$roleCode=if($role.code){$role.code}else{"SUPER_ADMIN"};$u="p4admin"+(Get-Date -Format HHmmss);$created=Api POST "/api/admin/accounts" @{username=$u;password="P4test123456";nickname="P4Admin";roleCode=$roleCode;permissions=@("dashboard:view")} $AdminToken -AllowFailure;$acc=GetRespData $created;$adminId=$acc.id;if($adminId){Api PATCH "/api/admin/accounts/$adminId/role" @{roleCode=$roleCode;useDefaultPermissions=$true} $AdminToken -AllowFailure|Out-Null;Api PUT "/api/admin/accounts/$adminId/permissions" @{roleCode=$roleCode;permissions=@("dashboard:view")} $AdminToken -AllowFailure|Out-Null;Api PATCH "/api/admin/accounts/$adminId/disable" $null $AdminToken -AllowFailure|Out-Null;Api PATCH "/api/admin/accounts/$adminId/enable" $null $AdminToken -AllowFailure|Out-Null};"adminId=$adminId username=$u roleCode=$roleCode"}
Case "P4RefundReconcile" "refund list and reconcile handle" {if($script:Context.orderId){Api POST "/api/orders/$($script:Context.orderId)/refund" @{reason="P4 refund";items=@()} $UserToken -AllowFailure|Out-Null};Api GET '/api/admin/pays/refunds?page=1&size=10' $null $AdminToken|Out-Null;Api GET "/api/admin/pays/$($script:Context.orderNo)/refunds?page=1&size=10" $null $AdminToken -AllowFailure|Out-Null;$recs=Api GET '/api/admin/reconciliations/pay-records?page=1&size=10' $null $AdminToken;$first=First (GetRespData $recs);$recordId=$first.id;if($recordId){Api POST "/api/admin/reconciliations/pay-records/$recordId/done" @{remark="P4 done"} $AdminToken -AllowFailure|Out-Null;Api POST "/api/admin/reconciliations/pay-records/$recordId/ignore" @{remark="P4 ignore"} $AdminToken -AllowFailure|Out-Null};"orderNo=$($script:Context.orderNo) payRecordId=$recordId"}
Case "P4UploadNegative" "upload negative matrix" {$a=Api POST "/api/files/avatar" $null $UserToken -AllowFailure;$b=Api POST "/api/files/product-image" $null $UserToken -AllowFailure;if($a.success -ne $false){throw "empty upload not rejected"};if($b.success -ne $false){throw "user product upload not rejected"};"upload negative checked"}
Case "P4PermissionDeep" "permission deep matrix" {$a=Api GET '/api/admin/accounts?page=1&size=10' $null $UserToken -AllowFailure;$b=Api GET '/api/orders?page=1&size=10' $null $AdminToken -AllowFailure;$c=Api GET '/api/admin/products?page=1&size=10' $null "Bearer invalid-token" -AllowFailure;if($a.success -ne $false){throw "user admin not rejected"};if($b.success -ne $false){throw "admin user not rejected"};if($c.success -ne $false){throw "invalid token not rejected"};"permission matrix checked"}
Reports
}catch{Reports;throw}
if(($script:Results|?{$_.status -eq 'FAIL' -or $_.status -eq 'TIMEOUT' -or $_.status -eq 'BLOCKED'}).Count -gt 0){throw 'There are failed or blocked cases.'}
Write-Host "All P4 automated test cases completed" -ForegroundColor Green
