param(
    [string]$BaseUrl = "http://localhost:9090",
    [string]$UserToken = "Bearer c025e987-3b46-4cd9-805e-f5649166b8e5",
    [string]$AdminToken = "Bearer 7dd54bdd-ce10-4ec7-b258-b278df5733c7",
    [string]$ReportDir = "",
    [int]$SkuId = 1,
    [int]$RequestTimeoutSec = 12,
    [int]$BatchTimeoutSec = 180,
    [switch]$ContinueOnFailure
)
$ErrorActionPreference = "Stop"
$script:Results = New-Object System.Collections.Generic.List[object]
$script:Context = @{}
$script:StartTime = Get-Date
$script:BatchDeadline = (Get-Date).AddSeconds($BatchTimeoutSec)
if ([string]::IsNullOrWhiteSpace($ReportDir)) { $ReportDir = Join-Path $PSScriptRoot "..\test-reports" }
if (-not (Test-Path $ReportDir)) { New-Item -ItemType Directory -Force -Path $ReportDir | Out-Null }
$script:Stamp = Get-Date -Format "yyyyMMdd-HHmmss"
$script:InitialReportPath = Join-Path $ReportDir ("p5-business-flow-initial-{0}.md" -f $script:Stamp)
$script:DetailReportPath = Join-Path $ReportDir ("p5-business-flow-detail-{0}.md" -f $script:Stamp)
function AddResult([string]$Suite,[string]$Name,[string]$Status,[string]$Detail="",[int]$ElapsedMs=0){$script:Results.Add([pscustomobject]@{suite=$Suite;name=$Name;status=$Status;detail=$Detail;elapsedMs=$ElapsedMs;time=(Get-Date).ToString("yyyy-MM-dd HH:mm:ss")})|Out-Null}
function Deadline{if((Get-Date)-gt $script:BatchDeadline){throw "Batch timeout exceeded"}}
function Resp($r){if($null -eq $r){return $null};if($r.PSObject.Properties.Name -contains "data"){return $r.data};return $r}
function First($v){if($null -eq $v){return $null};if($v -is [System.Array]){if($v.Count -gt 0){return $v[0]};return $null};foreach($n in @("records","list","items","content","rows")){if($v.$n -and $v.$n.Count -gt 0){return $v.$n[0]}};return $null}
function StatusOf([string]$m){if($m -match 'TIMEOUT|timeout|timed out'){return 'TIMEOUT'};if($m -match '401|403|Unauthorized|Forbidden|permission'){return 'BLOCKED'};if($m -match 'missing|not found|precondition'){return 'SKIP'};return 'FAIL'}
function Api{param([string]$Method,[string]$Path,[object]$Body=$null,[string]$Token="",[switch]$AllowFailure,[int]$TimeoutSec=$RequestTimeoutSec)
    Deadline
    $headers=@{}; if($Token){$headers["Authorization"]=$Token}
    $params=@{Method=$Method;Uri="$BaseUrl$Path";Headers=$headers;ContentType="application/json; charset=utf-8";TimeoutSec=$TimeoutSec}
    if($null -ne $Body){$params.Body=($Body|ConvertTo-Json -Depth 30)}
    try{$r=Invoke-RestMethod @params}catch{$m="HTTP request failed: $Method $Path | $($_.Exception.Message)";if($_.Exception.Message -match 'timeout|timed out'){$m="TIMEOUT: $Method $Path exceeded ${TimeoutSec}s"};if($AllowFailure){return [pscustomobject]@{success=$false;message=$m;data=$null}};if($m -like 'TIMEOUT:*'){throw [System.TimeoutException]::new($m)};throw $m}
    if($r.PSObject.Properties.Name -contains "success" -and $r.success -eq $false){if($AllowFailure){return $r};$msg=if($r.message){$r.message}else{$r.msg};throw "Business response failed: $Method $Path | $msg"}
    return $r
}
function Case([string]$Suite,[string]$Name,[scriptblock]$Block){Deadline;$sw=[System.Diagnostics.Stopwatch]::StartNew();try{$d=& $Block;$sw.Stop();AddResult $Suite $Name "PASS" ([string]$d) $sw.ElapsedMilliseconds;Write-Host "[PASS] $Suite - $Name" -ForegroundColor Green}catch [System.TimeoutException]{$sw.Stop();AddResult $Suite $Name "TIMEOUT" $_.Exception.Message $sw.ElapsedMilliseconds;Write-Host "[TIMEOUT] $Suite - $Name" -ForegroundColor Yellow;if(-not $ContinueOnFailure){throw}}catch{$sw.Stop();$st=StatusOf $_.Exception.Message;AddResult $Suite $Name $st $_.Exception.Message $sw.ElapsedMilliseconds;Write-Host "[$st] $Suite - $Name : $($_.Exception.Message)" -ForegroundColor Red;if(-not $ContinueOnFailure -and $st -eq "FAIL"){throw}}}
function WriteInitial{$lines=@("# mallFei P5 Initial Report","","- BaseUrl: $BaseUrl","- StartedAt: $($script:StartTime.ToString('yyyy-MM-dd HH:mm:ss'))","- RequestTimeoutSec: $RequestTimeoutSec","- BatchTimeoutSec: $BatchTimeoutSec","","## Planned cases","- P5Setup create paid order","- P5IdempotentPay duplicate pay order and callback","- P5IdempotentRefund duplicate refund and review","- P5OrderRepeat duplicate ship complete close","- P5StockRepeat duplicate stock reserve cancel","- P5ParamMatrix invalid parameters","- P5ReconcileRepeat duplicate reconcile handling");$lines|Set-Content -Path $script:InitialReportPath -Encoding UTF8;Write-Host "Initial report written: $script:InitialReportPath" -ForegroundColor Cyan}
function WriteDetail{$pass=($script:Results|Where-Object status -eq "PASS").Count;$fail=($script:Results|Where-Object status -eq "FAIL").Count;$timeout=($script:Results|Where-Object status -eq "TIMEOUT").Count;$skip=($script:Results|Where-Object status -eq "SKIP").Count;$blocked=($script:Results|Where-Object status -eq "BLOCKED").Count;$warn=($script:Results|Where-Object status -eq "WARN").Count;$lines=New-Object System.Collections.Generic.List[string];foreach($l in @("# mallFei P5 Detail Report","","- BaseUrl: $BaseUrl","- StartedAt: $($script:StartTime.ToString('yyyy-MM-dd HH:mm:ss'))","- PASS: $pass","- FAIL: $fail","- TIMEOUT: $timeout","- SKIP: $skip","- BLOCKED: $blocked","- WARN: $warn","","| Suite | Case | Status | ElapsedMs | Detail |","| --- | --- | --- | ---: | --- |")){$lines.Add($l)|Out-Null};foreach($r in $script:Results){$lines.Add("| $($r.suite) | $($r.name) | $($r.status) | $($r.elapsedMs) | $(($r.detail -replace '\|','\\|')) |")|Out-Null};$lines|Set-Content -Path $script:DetailReportPath -Encoding UTF8;Write-Host "Final report written: $script:DetailReportPath" -ForegroundColor Cyan}
function PaidOrder{$o=Api POST "/api/orders" @{receiverName="P5 User";receiverPhone="13800000000";receiverProvinceName="Beijing";receiverCityName="Beijing";receiverDistrictName="Chaoyang";receiverDetailAddress="P5 Address";remark="p5";items=@(@{skuId=$SkuId;quantity=1})} $UserToken;$od=Resp $o;$script:Context.orderId=$od.id;$script:Context.orderNo=$od.orderNo;$payPath="/api/pay/orders?orderNo=$($od.orderNo)" + "&payChannel=MOCK&returnPath=/orders";$p=Api POST $payPath $null $UserToken;$pd=Resp $p;$script:Context.payOrderNo=$pd.payOrderNo;Api POST "/api/pay/callback/mock-success?orderNo=$($od.orderNo)" $null $UserToken|Out-Null;"orderId=$($od.id) orderNo=$($od.orderNo) payOrderNo=$($pd.payOrderNo)"}
WriteInitial
try{
Case "P5Setup" "create paid order" {PaidOrder}
Case "P5IdempotentPay" "duplicate pay order and callback" {$no=$script:Context.orderNo;if(-not $no){throw "orderNo missing"};$payPath="/api/pay/orders?orderNo=$no" + "&payChannel=MOCK&returnPath=/orders";Api POST $payPath $null $UserToken -AllowFailure|Out-Null;Api POST $payPath $null $UserToken -AllowFailure|Out-Null;Api POST "/api/pay/callback/mock-success?orderNo=$no" $null $UserToken -AllowFailure|Out-Null;Api POST "/api/pay/callback/mock-success?orderNo=$no" $null $UserToken -AllowFailure|Out-Null;Api GET "/api/pay/reconcile?orderNo=$no" $null $UserToken|Out-Null;"orderNo=$no duplicate pay requests attempted"}
Case "P5IdempotentRefund" "duplicate refund and review" {$oid=$script:Context.orderId;if(-not $oid){throw "orderId missing"};$reason=([string]([char]0x5546)+[string]([char]0x54C1)+[string]([char]0x4E0E)+[string]([char]0x63CF)+[string]([char]0x8FF0)+[string]([char]0x4E0D)+[string]([char]0x7B26));Api POST "/api/orders/$oid/refund" @{reason=$reason;items=@()} $UserToken -AllowFailure|Out-Null;Api POST "/api/orders/$oid/refund" @{reason=$reason;items=@()} $UserToken -AllowFailure|Out-Null;$list=Api GET "/api/admin/aftersales?page=1&size=10" $null $AdminToken;$first=First (Resp $list);$aft=$first.aftersaleNo;if($aft){Api POST "/api/admin/aftersales/$aft/review" @{action="APPROVE";reason="P5 approve 1"} $AdminToken -AllowFailure|Out-Null;Api POST "/api/admin/aftersales/$aft/review" @{action="APPROVE";reason="P5 approve 2"} $AdminToken -AllowFailure|Out-Null};"orderId=$oid aftersaleNo=$aft"}
Case "P5OrderRepeat" "duplicate ship complete close" {$no=$script:Context.orderNo;if(-not $no){throw "orderNo missing"};Api PATCH "/api/admin/orders/$no/ship" $null $AdminToken -AllowFailure|Out-Null;Api PATCH "/api/admin/orders/$no/ship" $null $AdminToken -AllowFailure|Out-Null;Api PATCH "/api/admin/orders/$no/complete" $null $AdminToken -AllowFailure|Out-Null;Api PATCH "/api/admin/orders/$no/complete" $null $AdminToken -AllowFailure|Out-Null;Api DELETE "/api/admin/orders/$no" $null $AdminToken -AllowFailure|Out-Null;"orderNo=$no repeat order operations attempted"}
Case "P5StockRepeat" "duplicate stock reserve cancel" {$biz="P5-STOCK-"+(Get-Date -Format yyyyMMddHHmmss);$body=@{businessType="ORDER";businessNo=$biz;items=@(@{skuId=$SkuId;quantity=1})};Api POST "/api/internal/stocks/reserve" $body $AdminToken|Out-Null;Api POST "/api/internal/stocks/reserve" $body $AdminToken -AllowFailure|Out-Null;Api DELETE "/api/internal/stocks/cancel" $body $AdminToken|Out-Null;Api DELETE "/api/internal/stocks/cancel" $body $AdminToken -AllowFailure|Out-Null;"businessNo=$biz skuId=$SkuId"}
Case "P5ParamMatrix" "invalid parameter matrix" {$badProduct=Api POST "/api/admin/products" @{name="";categoryId=-1;skus=@(@{skuCode="";salePriceCent=-1;initialStock=-1})} $AdminToken -AllowFailure;$badAccount=Api POST "/api/admin/accounts" @{username="";password="";nickname="";roleCode="BAD_ROLE";permissions=@()} $AdminToken -AllowFailure;$badOrder=Api POST "/api/orders" @{receiverName="";items=@(@{skuId=-1;quantity=0})} $UserToken -AllowFailure;$badStock=Api PUT "/api/admin/stocks/$SkuId/adjust" @{adjustmentType="BAD";changeQuantity=-1;reason="BAD"} $AdminToken -AllowFailure;if($badProduct.success -ne $false -or $badAccount.success -ne $false -or $badOrder.success -ne $false -or $badStock.success -ne $false){throw "one or more invalid parameter requests were not rejected"};"bad product/account/order/stock parameters rejected"}
Case "P5ReconcileRepeat" "duplicate reconcile handling" {$r=Api GET "/api/admin/reconciliations/pay-records?page=1&size=10" $null $AdminToken;$first=First (Resp $r);$id=$first.id;if($id){Api POST "/api/admin/reconciliations/pay-records/$id/done" @{remark="P5 done 1"} $AdminToken -AllowFailure|Out-Null;Api POST "/api/admin/reconciliations/pay-records/$id/done" @{remark="P5 done 2"} $AdminToken -AllowFailure|Out-Null;Api POST "/api/admin/reconciliations/pay-records/$id/ignore" @{remark="P5 ignore"} $AdminToken -AllowFailure|Out-Null};"payRecordId=$id"}
WriteDetail
}catch{WriteDetail;throw}
if(($script:Results|Where-Object{$_.status -eq 'FAIL' -or $_.status -eq 'TIMEOUT' -or $_.status -eq 'BLOCKED'}).Count -gt 0){throw 'There are failed or blocked cases. Please check reports.'}
Write-Host "All P5 automated test cases completed" -ForegroundColor Green
