param(
  [string]$BaseUrl="http://localhost:9090",
  [string]$UserToken="Bearer c025e987-3b46-4cd9-805e-f5649166b8e5",
  [string]$AdminToken="Bearer 7dd54bdd-ce10-4ec7-b258-b278df5733c7",
  [string]$ReportDir="",
  [int]$SkuId=1,
  [int]$RequestTimeoutSec=12,
  [int]$BatchTimeoutSec=180,
  [switch]$ContinueOnFailure
)
$ErrorActionPreference="Stop"
$script:Results=New-Object System.Collections.Generic.List[object]
$script:StartTime=Get-Date
$script:BatchDeadline=(Get-Date).AddSeconds($BatchTimeoutSec)
if([string]::IsNullOrWhiteSpace($ReportDir)){ $ReportDir=Join-Path $PSScriptRoot "..\test-reports" }
if(-not(Test-Path $ReportDir)){ New-Item -ItemType Directory -Force -Path $ReportDir|Out-Null }
$script:Stamp=Get-Date -Format "yyyyMMdd-HHmmss"
$script:InitialReportPath=Join-Path $ReportDir ("p6-business-flow-initial-{0}.md" -f $script:Stamp)
$script:DetailReportPath=Join-Path $ReportDir ("p6-business-flow-detail-{0}.md" -f $script:Stamp)
function AddResult([string]$Suite,[string]$Name,[string]$Status,[string]$Detail="",[int]$ElapsedMs=0){$script:Results.Add([pscustomobject]@{suite=$Suite;name=$Name;status=$Status;detail=$Detail;elapsedMs=$ElapsedMs})|Out-Null}
function Deadline{if((Get-Date)-gt $script:BatchDeadline){throw "Batch timeout exceeded"}}
function Resp($r){if($null -eq $r){return $null};if($r.PSObject.Properties.Name -contains "data"){return $r.data};return $r}
function StatusOf([string]$m){if($m -match 'TIMEOUT|timeout|timed out'){return 'TIMEOUT'};if($m -match '401|403|Unauthorized|Forbidden|permission'){return 'BLOCKED'};return 'FAIL'}
function Api{param([string]$Method,[string]$Path,[object]$Body=$null,[string]$Token="",[switch]$AllowFailure)
  Deadline;$headers=@{};if($Token){$headers["Authorization"]=$Token};$params=@{Method=$Method;Uri="$BaseUrl$Path";Headers=$headers;ContentType="application/json; charset=utf-8";TimeoutSec=$RequestTimeoutSec};if($null -ne $Body){$params.Body=($Body|ConvertTo-Json -Depth 30)}
  try{$r=Invoke-RestMethod @params}catch{$m="HTTP request failed: $Method $Path | $($_.Exception.Message)";if($_.Exception.Message -match 'timeout|timed out'){$m="TIMEOUT: $Method $Path exceeded ${RequestTimeoutSec}s"};if($AllowFailure){return [pscustomobject]@{success=$false;message=$m;data=$null}};if($m -like 'TIMEOUT:*'){throw [System.TimeoutException]::new($m)};throw $m}
  if($r.PSObject.Properties.Name -contains "success" -and $r.success -eq $false){if($AllowFailure){return $r};$msg=if($r.message){$r.message}else{$r.msg};throw "Business response failed: $Method $Path | $msg"};return $r
}
function Case([string]$Suite,[string]$Name,[scriptblock]$Block){$sw=[System.Diagnostics.Stopwatch]::StartNew();try{$d=& $Block;$sw.Stop();AddResult $Suite $Name "PASS" ([string]$d) $sw.ElapsedMilliseconds;Write-Host "[PASS] $Suite - $Name" -ForegroundColor Green}catch [System.TimeoutException]{$sw.Stop();AddResult $Suite $Name "TIMEOUT" $_.Exception.Message $sw.ElapsedMilliseconds;Write-Host "[TIMEOUT] $Suite - $Name" -ForegroundColor Yellow;if(-not $ContinueOnFailure){throw}}catch{$sw.Stop();$st=StatusOf $_.Exception.Message;AddResult $Suite $Name $st $_.Exception.Message $sw.ElapsedMilliseconds;Write-Host "[$st] $Suite - $Name : $($_.Exception.Message)" -ForegroundColor Red;if(-not $ContinueOnFailure -and $st -eq "FAIL"){throw}}}
function WriteInitial{$lines=@("# mallFei P6 Initial Report","","- BaseUrl: $BaseUrl","- StartedAt: $($script:StartTime.ToString('yyyy-MM-dd HH:mm:ss'))","- RequestTimeoutSec: $RequestTimeoutSec","- BatchTimeoutSec: $BatchTimeoutSec","","## Planned cases","- P6Public public product and health checks","- P6File upload success and negative checks","- P6StockOps stock operation checks","- P6AdminList admin list endpoint checks","- P6FinalMatrix permission and parameter matrix","- P6Summary coverage summary");$lines|Set-Content -Path $script:InitialReportPath -Encoding UTF8;Write-Host "Initial report written: $script:InitialReportPath" -ForegroundColor Cyan}
function WriteDetail{$pass=($script:Results|Where-Object status -eq "PASS").Count;$fail=($script:Results|Where-Object status -eq "FAIL").Count;$timeout=($script:Results|Where-Object status -eq "TIMEOUT").Count;$blocked=($script:Results|Where-Object status -eq "BLOCKED").Count;$lines=New-Object System.Collections.Generic.List[string];foreach($l in @("# mallFei P6 Detail Report","","- BaseUrl: $BaseUrl","- StartedAt: $($script:StartTime.ToString('yyyy-MM-dd HH:mm:ss'))","- PASS: $pass","- FAIL: $fail","- TIMEOUT: $timeout","- BLOCKED: $blocked","","| Suite | Case | Status | ElapsedMs | Detail |","| --- | --- | --- | ---: | --- |")){$lines.Add($l)|Out-Null};foreach($r in $script:Results){$lines.Add("| $($r.suite) | $($r.name) | $($r.status) | $($r.elapsedMs) | $(($r.detail -replace '\|','\\|')) |")|Out-Null};$lines|Set-Content -Path $script:DetailReportPath -Encoding UTF8;Write-Host "Final report written: $script:DetailReportPath" -ForegroundColor Cyan}
function UploadFile([string]$Uri,[string]$Token,[string]$Content){$tmp=Join-Path $env:TEMP ("p6-smoke-"+[guid]::NewGuid().ToString()+".txt");Set-Content -Path $tmp -Value $Content -Encoding UTF8;try{$boundary="----P6Smoke"+[guid]::NewGuid().ToString("N");$bytes=[System.IO.File]::ReadAllBytes($tmp);$head=[System.Text.Encoding]::UTF8.GetBytes("--$boundary`r`nContent-Disposition: form-data; name=`"file`"; filename=`"p6-smoke.txt`"`r`nContent-Type: text/plain`r`n`r`n");$tail=[System.Text.Encoding]::UTF8.GetBytes("`r`n--$boundary--`r`n");$body=New-Object byte[] ($head.Length+$bytes.Length+$tail.Length);[System.Buffer]::BlockCopy($head,0,$body,0,$head.Length);[System.Buffer]::BlockCopy($bytes,0,$body,$head.Length,$bytes.Length);[System.Buffer]::BlockCopy($tail,0,$body,$head.Length+$bytes.Length,$tail.Length);Invoke-RestMethod -Method Post -Uri $Uri -Headers @{Authorization=$Token} -ContentType "multipart/form-data; boundary=$boundary" -Body $body -TimeoutSec $RequestTimeoutSec|Out-Null}finally{Remove-Item $tmp -Force -ErrorAction SilentlyContinue}}
WriteInitial
try{
Case "P6Public" "public product and health checks" {Api GET '/api/categories' $null $UserToken|Out-Null;Api GET '/api/products?page=1&size=10' $null $UserToken|Out-Null;Api GET '/api/products/1' $null $UserToken|Out-Null;Api GET '/api/internal/stocks/health' $null $UserToken|Out-Null;Api GET '/api/internal/stocks/1' $null $UserToken|Out-Null;"public and health endpoints checked"}
Case "P6File" "file upload success and negative checks" {UploadFile "$BaseUrl/api/files/avatar" $UserToken "p6 avatar";UploadFile "$BaseUrl/api/files/product-image" $AdminToken "p6 product image";$empty=Api POST '/api/files/avatar' $null $UserToken -AllowFailure;if($empty.success -ne $false){throw "empty file upload not rejected"};"file upload success and empty-file rejection checked"}
Case "P6StockOps" "stock operations check" {$biz="P6-STOCK-"+(Get-Date -Format yyyyMMddHHmmss);$body=@{businessType="ORDER";businessNo=$biz;items=@(@{skuId=$SkuId;quantity=1})};Api POST '/api/internal/stocks/reserve' $body $AdminToken|Out-Null;Api DELETE '/api/internal/stocks/cancel' $body $AdminToken|Out-Null;Api PUT '/api/internal/stocks/restore' $body $AdminToken|Out-Null;"businessNo=$biz stock reserve/cancel/restore checked"}
Case "P6AdminList" "admin list endpoints check" {Api GET '/api/admin/orders?page=1&size=10' $null $AdminToken|Out-Null;Api GET '/api/admin/pays?page=1&size=10' $null $AdminToken|Out-Null;Api GET '/api/admin/pays/refunds?page=1&size=10' $null $AdminToken|Out-Null;Api GET '/api/admin/aftersales?page=1&size=10' $null $AdminToken|Out-Null;Api GET '/api/admin/accounts?page=1&size=10' $null $AdminToken|Out-Null;Api GET '/api/admin/products?page=1&size=10' $null $AdminToken|Out-Null;Api GET '/api/admin/stocks?page=1&size=10' $null $AdminToken|Out-Null;Api GET '/api/admin/reconciliations/pay-records?page=1&size=10' $null $AdminToken|Out-Null;Api GET '/api/admin/online-reconcile-tasks?page=1&size=10' $null $AdminToken|Out-Null;"admin list endpoints checked"}
Case "P6FinalMatrix" "final permission and parameter matrix" {$a=Api GET '/api/admin/dashboard' $null $UserToken -AllowFailure;$b=Api GET '/api/orders?page=1&size=10' $null "Bearer invalid-token" -AllowFailure;$c=Api POST '/api/orders' @{receiverName="";items=@()} $UserToken -AllowFailure;$d=Api POST '/api/admin/products' @{name="";categoryId=-1;skus=@()} $AdminToken -AllowFailure;if($a.success -ne $false -or $b.success -ne $false -or $c.success -ne $false -or $d.success -ne $false){throw "one or more invalid requests were not rejected"};"final permission and parameter matrix checked"}
Case "P6Summary" "coverage summary" {"P0-P5 coverage summary prepared"}
WriteDetail
}catch{WriteDetail;throw}
if(($script:Results|Where-Object{$_.status -eq 'FAIL' -or $_.status -eq 'TIMEOUT' -or $_.status -eq 'BLOCKED'}).Count -gt 0){throw 'There are failed or blocked cases. Please check reports.'}
Write-Host "All P6 automated test cases completed" -ForegroundColor Green
