CREATE TABLE IF NOT EXISTS pay_reconcile_task (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    task_no VARCHAR(64) NOT NULL UNIQUE,
    reconcile_date DATE NOT NULL,
    channel VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'CREATED',
    local_bill_status VARCHAR(32) NOT NULL DEFAULT 'EMPTY',
    channel_bill_status VARCHAR(32) NOT NULL DEFAULT 'EMPTY',
    match_status VARCHAR(32) NOT NULL DEFAULT 'NOT_MATCHED',
    local_total_count BIGINT NOT NULL DEFAULT 0,
    local_total_amount_cent BIGINT NOT NULL DEFAULT 0,
    channel_total_count BIGINT NOT NULL DEFAULT 0,
    channel_total_amount_cent BIGINT NOT NULL DEFAULT 0,
    matched_count BIGINT NOT NULL DEFAULT 0,
    diff_count BIGINT NOT NULL DEFAULT 0,
    pending_count BIGINT NOT NULL DEFAULT 0,
    done_count BIGINT NOT NULL DEFAULT 0,
    hang_count BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(64) NULL,
    completed_by VARCHAR(64) NULL,
    remark VARCHAR(512) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    matched_at DATETIME NULL,
    completed_at DATETIME NULL,
    KEY idx_reconcile_date_channel (reconcile_date, channel),
    KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS pay_reconcile_local_bill_item (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    task_id BIGINT NOT NULL,
    biz_type VARCHAR(16) NOT NULL,
    order_no VARCHAR(64) NULL,
    pay_order_no VARCHAR(64) NULL,
    refund_no VARCHAR(64) NULL,
    user_id BIGINT NULL,
    local_status VARCHAR(64) NULL,
    order_status VARCHAR(64) NULL,
    amount_cent BIGINT NULL,
    channel VARCHAR(32) NULL,
    transaction_no VARCHAR(128) NULL,
    trade_time DATETIME NULL,
    raw_snapshot TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_task_biz (task_id, biz_type),
    KEY idx_pay_order_no (pay_order_no),
    KEY idx_refund_no (refund_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS pay_reconcile_channel_bill_item (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    task_id BIGINT NOT NULL,
    biz_type VARCHAR(16) NOT NULL,
    channel VARCHAR(32) NOT NULL,
    out_trade_no VARCHAR(64) NULL,
    order_no VARCHAR(64) NULL,
    pay_order_no VARCHAR(64) NULL,
    refund_no VARCHAR(64) NULL,
    channel_trade_no VARCHAR(128) NULL,
    channel_refund_no VARCHAR(128) NULL,
    channel_status VARCHAR(64) NULL,
    amount_cent BIGINT NULL,
    fee_cent BIGINT NOT NULL DEFAULT 0,
    trade_time DATETIME NULL,
    raw_line TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_task_biz (task_id, biz_type),
    KEY idx_out_trade_no (out_trade_no),
    KEY idx_refund_no (refund_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS pay_reconcile_diff_item (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    task_id BIGINT NOT NULL,
    biz_type VARCHAR(16) NOT NULL,
    diff_type VARCHAR(64) NOT NULL,
    diff_level VARCHAR(16) NOT NULL,
    order_no VARCHAR(64) NULL,
    pay_order_no VARCHAR(64) NULL,
    refund_no VARCHAR(64) NULL,
    local_item_id BIGINT NULL,
    channel_item_id BIGINT NULL,
    local_status VARCHAR(64) NULL,
    channel_status VARCHAR(64) NULL,
    local_amount_cent BIGINT NULL,
    channel_amount_cent BIGINT NULL,
    diff_amount_cent BIGINT NULL,
    suggested_action VARCHAR(64) NULL,
    process_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    process_remark VARCHAR(512) NULL,
    processed_by VARCHAR(64) NULL,
    processed_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_task_status (task_id, process_status),
    KEY idx_task_diff (task_id, diff_type),
    KEY idx_order_no (order_no),
    KEY idx_pay_order_no (pay_order_no),
    KEY idx_refund_no (refund_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS pay_reconcile_operation_log (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    task_id BIGINT NOT NULL,
    diff_item_id BIGINT NULL,
    operation_type VARCHAR(64) NOT NULL,
    operation_content VARCHAR(512) NULL,
    before_snapshot TEXT NULL,
    after_snapshot TEXT NULL,
    operator_id VARCHAR(64) NULL,
    operator_name VARCHAR(64) NULL,
    remark VARCHAR(512) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_task_id (task_id),
    KEY idx_diff_item_id (diff_item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
