CREATE TABLE IF NOT EXISTS `pay_callback_record` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `channel` VARCHAR(32) NOT NULL COMMENT '支付渠道',
  `callback_type` VARCHAR(16) NOT NULL COMMENT '回调类型：PAY/REFUND',
  `pay_order_no` VARCHAR(64) DEFAULT NULL COMMENT '支付单号',
  `refund_no` VARCHAR(64) DEFAULT NULL COMMENT '退款单号',
  `order_no` VARCHAR(64) DEFAULT NULL COMMENT '订单号',
  `out_trade_no` VARCHAR(64) DEFAULT NULL COMMENT '渠道交易单号',
  `transaction_no` VARCHAR(64) DEFAULT NULL COMMENT '支付渠道交易号',
  `amount_cent` BIGINT DEFAULT NULL COMMENT '金额(分)',
  `trade_status` VARCHAR(32) DEFAULT NULL COMMENT '交易状态',
  `signature` VARCHAR(2048) DEFAULT NULL COMMENT '签名',
  `verified` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否验签通过',
  `process_status` VARCHAR(32) NOT NULL DEFAULT 'RECEIVED' COMMENT '处理状态',
  `fail_reason` VARCHAR(512) DEFAULT NULL COMMENT '失败原因',
  `raw_payload` LONGTEXT COMMENT '原始回调报文',
  `callback_time` DATETIME(3) DEFAULT NULL COMMENT '回调时间',
  `processed_at` DATETIME(3) DEFAULT NULL COMMENT '处理时间',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_pay_callback_record_transaction_no` (`transaction_no`),
  KEY `idx_pay_callback_record_out_trade_no` (`out_trade_no`),
  KEY `idx_pay_callback_record_pay_order_no` (`pay_order_no`),
  KEY `idx_pay_callback_record_order_no` (`order_no`),
  KEY `idx_pay_callback_record_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支付回调记录表';
