<template>
<AdminLayout :title="text('title')" @refresh="loadStocks" @logout="handleLogout">
<el-card class="admin-page-card"><el-form :inline="true" :model="filters" class="admin-filter-form">
<el-form-item :label="text('skuId')"><el-input v-model="filters.skuId" :placeholder="text('skuPlaceholder')" clearable /></el-form-item>
<el-form-item :label="text('stockStatus')"><el-select v-model="filters.stockStatus" clearable :placeholder="text('selectStockStatus')" style="width:160px"><el-option :label="text('active')" value="ACTIVE" /><el-option :label="text('frozen')" value="FROZEN" /><el-option :label="text('offline')" value="OFFLINE" /></el-select></el-form-item>
<el-form-item :label="text('warningStatus')"><el-select v-model="filters.warningStatus" clearable :placeholder="text('selectWarningStatus')" style="width:160px"><el-option :label="text('normal')" value="NORMAL" /><el-option :label="text('low')" value="LOW" /><el-option :label="text('high')" value="HIGH" /></el-select></el-form-item>
<el-form-item><el-button type="primary" @click="handleSearch">{{ text('search') }}</el-button></el-form-item><el-form-item><el-button @click="handleReset">{{ text('reset') }}</el-button></el-form-item><el-form-item><el-button @click="exportStocks">{{ text('export') }}</el-button></el-form-item>
</el-form></el-card>
<el-card><el-table v-loading="loading" :data="stocks" class="admin-table" :empty-text="text('noData')" @sort-change="handleSortChange">
<el-table-column prop="skuId" :label="text('skuId')" width="100" sortable="custom" />
<el-table-column prop="availableStock" :label="text('available')" width="120" sortable="custom" />
<el-table-column prop="lockedStock" :label="text('locked')" width="120" sortable="custom" />
<el-table-column prop="totalStock" :label="text('total')" width="120" sortable="custom" />
<el-table-column prop="stockStatus" :label="text('stockStatus')" width="120" sortable="custom"><template #default="{ row }"><el-tag :type="stockStatusMeta(row.stockStatus).type">{{ stockStatusMeta(row.stockStatus).label }}</el-tag></template></el-table-column>
<el-table-column prop="warningStatus" :label="text('warningStatus')" width="120" sortable="custom"><template #default="{ row }"><el-tag :type="stockWarningMeta(row.warningStatus).type">{{ stockWarningMeta(row.warningStatus).label }}</el-tag></template></el-table-column>
<el-table-column prop="lowStockThreshold" :label="text('lowThreshold')" width="100" sortable="custom" />
<el-table-column prop="highStockThreshold" :label="text('highThreshold')" width="100" sortable="custom" />
<el-table-column :label="text('actions')" min-width="320"><template #default="{ row }"><el-button size="small" @click="openAdjust(row)">{{ text('adjust') }}</el-button><el-button size="small" type="warning" @click="openPolicy(row)">{{ text('policy') }}</el-button><el-button v-if="row.warningStatus !== 'NORMAL'" size="small" type="danger" @click="openWarning(row)">{{ text('warningHandle') }}</el-button></template></el-table-column>
</el-table><div class="admin-pagination"><el-pagination background layout="sizes, prev, pager, next, total" :current-page="pager.page" :page-size="pager.size" :page-sizes="ADMIN_PAGE_SIZES" :total="pager.total" @current-change="handlePageChange" @size-change="handleSizeChange" /></div></el-card>
<el-dialog v-model="adjustVisible" :title="text('adjustTitle')" width="460px" append-to-body destroy-on-close align-center><el-form ref="adjustFormRef" :model="adjustForm" :rules="adjustRules" label-width="100px" class="admin-dialog-form"><el-form-item :label="text('total')" prop="totalStock"><el-input-number v-model="adjustForm.totalStock" :min="0" /></el-form-item><el-form-item :label="text('available')" prop="availableStock"><el-input-number v-model="adjustForm.availableStock" :min="0" /></el-form-item><el-form-item :label="text('locked')" prop="lockedStock"><el-input-number v-model="adjustForm.lockedStock" :min="0" /></el-form-item><el-form-item :label="text('reason')" prop="reason"><el-input v-model="adjustForm.reason" type="textarea" :rows="3" /></el-form-item></el-form><template #footer><el-button :disabled="adjustSubmitting" @click="adjustVisible=false">{{ text('cancel') }}</el-button><el-button type="primary" :loading="adjustSubmitting" @click="submitAdjust">{{ text('submit') }}</el-button></template></el-dialog>
<el-dialog v-model="policyVisible" :title="text('policyTitle')" width="460px" append-to-body destroy-on-close align-center><el-form ref="policyFormRef" :model="policyForm" :rules="policyRules" label-width="100px" class="admin-dialog-form"><el-form-item :label="text('stockStatus')" prop="stockStatus"><el-select v-model="policyForm.stockStatus" style="width:180px"><el-option :label="text('active')" value="ACTIVE" /><el-option :label="text('frozen')" value="FROZEN" /><el-option :label="text('offline')" value="OFFLINE" /></el-select></el-form-item><el-form-item :label="text('lowThreshold')" prop="lowStockThreshold"><el-input-number v-model="policyForm.lowStockThreshold" :min="0" /></el-form-item><el-form-item :label="text('highThreshold')" prop="highStockThreshold"><el-input-number v-model="policyForm.highStockThreshold" :min="0" /></el-form-item><el-form-item :label="text('policyReason')" prop="reason"><el-input v-model="policyForm.reason" type="textarea" :rows="3" /></el-form-item></el-form><template #footer><el-button :disabled="policySubmitting" @click="policyVisible=false">{{ text('cancel') }}</el-button><el-button type="primary" :loading="policySubmitting" @click="submitPolicy">{{ text('submit') }}</el-button></template></el-dialog>
<el-dialog v-model="warningVisible" :title="text('warningTitle')" width="460px" append-to-body destroy-on-close align-center><el-form ref="warningFormRef" :model="warningForm" :rules="warningRules" label-width="100px" class="admin-dialog-form"><el-form-item :label="text('action')" prop="action"><el-select v-model="warningForm.action" style="width:220px"><el-option :label="text('freezeStock')" value="FREEZE" /><el-option :label="text('recoverActive')" value="RECOVER_ACTIVE" /><el-option :label="text('offlineProduct')" value="OFFLINE" /></el-select></el-form-item><el-form-item :label="text('note')" prop="note"><el-input v-model="warningForm.note" type="textarea" :rows="3" /></el-form-item></el-form><template #footer><el-button :disabled="warningSubmitting" @click="warningVisible=false">{{ text('cancel') }}</el-button><el-button type="primary" :loading="warningSubmitting" @click="submitWarning">{{ text('submit') }}</el-button></template></el-dialog>
</AdminLayout>
</template>
<script setup>
import { nextTick, onActivated, onMounted, reactive, ref } from 'vue';import { ElMessage } from 'element-plus';import { useRoute, useRouter } from 'vue-router';import AdminLayout from '../components/AdminLayout.vue';import { adjustAdminStock, fetchAdminStocks, handleAdminStockWarning, updateAdminStockPolicy } from '../api';import { useAdminStore } from '../stores/admin';import { adminPageCache, isCacheFresh } from '../stores/pageCache';import { confirmAction } from '../utils/action';import { exportRowsToCsv } from '../utils/export';import { t } from '../utils/i18n';import { ADMIN_PAGE_SIZE, ADMIN_PAGE_SIZES } from '../utils/pagination';import { getStatusTagMeta } from '../utils/status';
const route=useRoute();const router=useRouter();const adminStore=useAdminStore();const loading=ref(false);const stocks=ref(adminPageCache.stocks.list || []);const currentSkuId=ref(null);const adjustVisible=ref(false);const policyVisible=ref(false);const warningVisible=ref(false);const adjustSubmitting=ref(false);const policySubmitting=ref(false);const warningSubmitting=ref(false);const adjustFormRef=ref();const policyFormRef=ref();const warningFormRef=ref();const filters=reactive({ ...adminPageCache.stocks.filters, skuId: String(route.query.skuId ?? adminPageCache.stocks.filters.skuId ?? '') , stockStatus: String(route.query.stockStatus ?? adminPageCache.stocks.filters.stockStatus ?? ''), warningStatus: String(route.query.warningStatus ?? adminPageCache.stocks.filters.warningStatus ?? '')});const query=reactive({ ...adminPageCache.stocks.query, sortBy:String(route.query.sortBy||adminPageCache.stocks.query.sortBy||'skuId'),sortOrder:String(route.query.sortOrder||adminPageCache.stocks.query.sortOrder||'asc')});const adjustForm=reactive({totalStock:0,availableStock:0,lockedStock:0,reason:''});const policyForm=reactive({stockStatus:'ACTIVE',lowStockThreshold:0,highStockThreshold:0,reason:''});const warningForm=reactive({action:'FREEZE',note:''});const pager=reactive({ page:Number(route.query.page||adminPageCache.stocks.pager.page||1), size:Number(route.query.size||adminPageCache.stocks.pager.size||ADMIN_PAGE_SIZE), total:Number(adminPageCache.stocks.pager.total||0) });const stockStatusMeta=(s)=>getStatusTagMeta('stockStatus',s);const stockWarningMeta=(s)=>getStatusTagMeta('stockWarning',s);const text=(key)=>t(`stockManage.${key}`);
const validateNonNegative=(_,value,callback)=>{if(value==null||value<0)return callback(new Error(text('validateNonNegative')));callback();};const validateRequiredText=(messageKey)=>(_,value,callback)=>{if(!value?.trim())return callback(new Error(text(messageKey)));callback();};const validatePolicyThreshold=(_,value,callback)=>{if(value==null||value<0)return callback(new Error(text('validateNonNegative')));if(policyForm.highStockThreshold<policyForm.lowStockThreshold)return callback(new Error(text('highThresholdLessThanLow')||'??????????'));callback();};const adjustRules={totalStock:[{validator:validateNonNegative,trigger:'change'}],availableStock:[{validator:validateNonNegative,trigger:'change'}],lockedStock:[{validator:validateNonNegative,trigger:'change'}],reason:[{validator:validateRequiredText('validateReasonRequired'),trigger:'blur'}]};const policyRules={stockStatus:[{required:true,message:text('selectStockStatus'),trigger:'change'}],lowStockThreshold:[{validator:validatePolicyThreshold,trigger:'change'}],highStockThreshold:[{validator:validatePolicyThreshold,trigger:'change'}],reason:[{validator:validateRequiredText('validateReasonRequired'),trigger:'blur'}]};const warningRules={action:[{required:true,message:text('action'),trigger:'change'}],note:[{validator:validateRequiredText('note'),trigger:'blur'}]};
const syncRoute=async()=>{await router.replace({path:'/stocks',query:{...(filters.skuId?{skuId:String(filters.skuId)}:{}),...(filters.stockStatus?{stockStatus:filters.stockStatus}:{}),...(filters.warningStatus?{warningStatus:filters.warningStatus}:{}),...(query.sortBy?{sortBy:query.sortBy}:{}),...(query.sortOrder?{sortOrder:query.sortOrder}:{}),...(pager.page>1?{page:String(pager.page)}:{}),...(pager.size!==ADMIN_PAGE_SIZE?{size:String(pager.size)}:{})}})};
const loadStocks=async()=>{loading.value=true;try{const {data}=await fetchAdminStocks({skuId:filters.skuId||undefined,stockStatus:filters.stockStatus||undefined,warningStatus:filters.warningStatus||undefined,sortBy:query.sortBy||undefined,sortOrder:query.sortOrder||undefined,page:pager.page,size:pager.size});stocks.value=data.data.records||[];pager.total=data.data.total||0;adminPageCache.stocks.list=stocks.value;adminPageCache.stocks.filters={skuId:filters.skuId,stockStatus:filters.stockStatus,warningStatus:filters.warningStatus};adminPageCache.stocks.query={sortBy:query.sortBy,sortOrder:query.sortOrder};adminPageCache.stocks.pager={page:pager.page,size:pager.size,total:pager.total};adminPageCache.stocks.loaded=true;adminPageCache.stocks.updatedAt=Date.now();}catch(error){ElMessage.error(error?.response?.data?.message||text('loadFailed'));}finally{loading.value=false;}};
const exportStocks=()=>exportRowsToCsv(text('exportName'),stocks.value,[{label:text('skuId'),value:'skuId'},{label:text('available'),value:'availableStock'},{label:text('locked'),value:'lockedStock'},{label:text('total'),value:'totalStock'},{label:text('stockStatus'),value:'stockStatus'},{label:text('warningStatus'),value:'warningStatus'},{label:text('lowThreshold'),value:'lowStockThreshold'},{label:text('highThreshold'),value:'highStockThreshold'}]);
const handleSearch=async()=>{pager.page=1;await syncRoute();await loadStocks();};const handleReset=async()=>{filters.skuId='';filters.stockStatus='';filters.warningStatus='';query.sortBy='skuId';query.sortOrder='asc';pager.page=1;pager.size=ADMIN_PAGE_SIZE;await syncRoute();await loadStocks();};const handlePageChange=async(page)=>{pager.page=page;await syncRoute();await loadStocks();};const handleSizeChange=async(size)=>{pager.size=size;pager.page=1;await syncRoute();await loadStocks();};const handleSortChange=async({prop,order})=>{query.sortBy=prop||'skuId';query.sortOrder=order==='descending'?'desc':'asc';pager.page=1;await syncRoute();await loadStocks();};const resetAdjustValidation=async()=>{await nextTick();adjustFormRef.value?.clearValidate();};const resetPolicyValidation=async()=>{await nextTick();policyFormRef.value?.clearValidate();};const resetWarningValidation=async()=>{await nextTick();warningFormRef.value?.clearValidate();};const openAdjust=async(row)=>{currentSkuId.value=row.skuId;Object.assign(adjustForm,{totalStock:row.totalStock,availableStock:row.availableStock,lockedStock:row.lockedStock,reason:''});adjustVisible.value=true;await resetAdjustValidation();};const openPolicy=async(row)=>{currentSkuId.value=row.skuId;Object.assign(policyForm,{stockStatus:row.stockStatus,lowStockThreshold:row.lowStockThreshold,highStockThreshold:row.highStockThreshold,reason:''});policyVisible.value=true;await resetPolicyValidation();};const openWarning=async(row)=>{currentSkuId.value=row.skuId;Object.assign(warningForm,{action:row.warningStatus==='LOW'?'FREEZE':'OFFLINE',note:''});warningVisible.value=true;await resetWarningValidation();};
const submitAdjust=async()=>{const valid=await adjustFormRef.value?.validate().catch(()=>false);if(!valid)return;if(adjustForm.totalStock!==adjustForm.availableStock+adjustForm.lockedStock){ElMessage.warning(text('validateSumMismatch'));return;}try{await confirmAction(`${text('adjust')} SKU ${currentSkuId.value}`);adjustSubmitting.value=true;await adjustAdminStock(currentSkuId.value,{...adjustForm});ElMessage.success(text('adjustSuccess'));adjustVisible.value=false;await loadStocks();}catch(error){if(error!=='cancel')ElMessage.error(error?.response?.data?.message||text('adjustFailed'));}finally{adjustSubmitting.value=false;}};const submitPolicy=async()=>{const valid=await policyFormRef.value?.validate().catch(()=>false);if(!valid)return;try{await confirmAction(`${text('policy')} SKU ${currentSkuId.value}`);policySubmitting.value=true;await updateAdminStockPolicy(currentSkuId.value,{...policyForm});ElMessage.success(text('policySuccess'));policyVisible.value=false;await loadStocks();}catch(error){if(error!=='cancel')ElMessage.error(error?.response?.data?.message||text('policyFailed'));}finally{policySubmitting.value=false;}};const submitWarning=async()=>{const valid=await warningFormRef.value?.validate().catch(()=>false);if(!valid)return;try{await confirmAction(`${text('warningHandle')} SKU ${currentSkuId.value}`);warningSubmitting.value=true;await handleAdminStockWarning(currentSkuId.value,{...warningForm});ElMessage.success(text('warningSuccess'));warningVisible.value=false;await loadStocks();}catch(error){if(error!=='cancel')ElMessage.error(error?.response?.data?.message||text('warningFailed'));}finally{warningSubmitting.value=false;}};const handleLogout=async()=>{await adminStore.logout();router.push('/login');};const initializeStocksPage=async(force=false)=>{if(!force&&adminPageCache.stocks.loaded&&stocks.value.length&&isCacheFresh(adminPageCache.stocks.updatedAt)){return;}await loadStocks();};onMounted(()=>initializeStocksPage());onActivated(()=>initializeStocksPage());
</script>
