export function getStatusTagMeta(kind, value) {
  const normalized = String(value || '').toUpperCase();

  const maps = {
    order: {
      WAIT_PAY: { label: '待支付', type: 'warning' },
      WAIT_PAYMENT: { label: '待支付', type: 'warning' },
      WAITING_PAYMENT: { label: '待支付', type: 'warning' },
      PAY_WAIT: { label: '待支付', type: 'warning' },
      PAY_PENDING: { label: '待支付', type: 'warning' },
      PENDING_PAYMENT: { label: '待支付', type: 'warning' },
      PAYMENT_EXCEPTION: { label: '支付异常', type: 'danger' },
      PAID: { label: '已支付', type: 'primary' },
      PROCESSING: { label: '处理中', type: 'primary' },
      SHIPPED: { label: '已发货', type: 'primary' },
      COMPLETED: { label: '已完成', type: 'success' },
      CANCELLED: { label: '已取消', type: 'info' },
      TIMEOUT_CANCEL: { label: '超时取消', type: 'danger' },
      TIMEOUT_CANCELED: { label: '超时取消', type: 'danger' },
      TIMEOUT_CANCELLED: { label: '超时取消', type: 'danger' },
      CANCEL_TIMEOUT: { label: '超时取消', type: 'danger' },
      REFUND_PENDING: { label: '售后中', type: 'warning' },
      REFUNDING: { label: '退款处理中', type: 'primary' },
      REFUNDED: { label: '已退款', type: 'success' },
      REFUND_SUCCESS: { label: '已退款', type: 'success' },
      REFUND_FAILED: { label: '退款失败', type: 'danger' },
      REFUND_CLOSED: { label: '退款关闭', type: 'info' },
      PARTIALLY_REFUNDED: { label: '部分退款', type: 'warning' },
      CLOSED: { label: '已关闭', type: 'info' },
    },
    pay: {
      PENDING: { label: '待支付', type: 'warning' },
      PAYING: { label: '支付中', type: 'primary' },
      SUCCESS: { label: '支付成功', type: 'success' },
      FAILED: { label: '支付失败', type: 'danger' },
      CLOSED: { label: '已关闭', type: 'info' },
      REFUND_PENDING: { label: '退款待处理', type: 'warning' },
      REFUNDING: { label: '退款中', type: 'primary' },
      PARTIALLY_REFUNDED: { label: '部分退款', type: 'warning' },
      REFUNDED: { label: '已退款', type: 'success' },
      REFUND_FAILED: { label: '退款失败', type: 'danger' },
    },
    refund: {
      REFUND_PENDING: { label: '退款申请', type: 'warning' },
      REFUNDING: { label: '退款处理中', type: 'primary' },
      REFUND_SUCCESS: { label: '退款成功', type: 'success' },
      REFUND_FAILED: { label: '退款失败', type: 'danger' },
      REFUND_CLOSED: { label: '退款关闭', type: 'info' },
    },
    callbackProcess: {
      RECEIVED: { label: '已接收', type: 'info' },
      VERIFY_FAILED: { label: '验签失败', type: 'danger' },
      BUSINESS_MISMATCH: { label: '业务不匹配', type: 'danger' },
      AMOUNT_MISMATCH: { label: '金额不一致', type: 'danger' },
      IGNORED_DUPLICATE: { label: '重复忽略', type: 'info' },
      IGNORED_NON_SUCCESS: { label: '非成功忽略', type: 'info' },
      PROCESSED: { label: '处理成功', type: 'success' },
      PROCESS_FAILED: { label: '处理失败', type: 'danger' },
    },
    aftersale: {
      NONE: { label: '无售后', type: 'info' },
      PENDING_REVIEW: { label: '待审核', type: 'warning' },
      APPROVED: { label: '审核通过', type: 'success' },
      REJECTED: { label: '审核驳回', type: 'danger' },
      REFUND_PENDING: { label: '退款待处理', type: 'warning' },
      REFUNDING: { label: '退款处理中', type: 'primary' },
      REFUND_PROCESSING: { label: '退款处理中', type: 'primary' },
      REFUND_SUCCESS: { label: '退款成功', type: 'success' },
      REFUNDED: { label: '退款成功', type: 'success' },
      REFUND_FAILED: { label: '退款失败', type: 'danger' },
      REFUND_CLOSED: { label: '退款关闭', type: 'info' },
      CANCELLED: { label: '已取消', type: 'info' },
    },
    reconcile: {
      CONSISTENT: { label: '一致', type: 'success' },
      ABNORMAL: { label: '异常', type: 'danger' },
    },
    stockReconcile: {
      CONSISTENT: { label: '一致', type: 'success' },
      INCONSISTENT: { label: '不一致', type: 'danger' },
      REPAIRED: { label: '已修复', type: 'success' },
      IGNORED: { label: '已忽略', type: 'info' },
    },
    stockRepair: {
      NONE: { label: '无需处理', type: 'success' },
      PENDING: { label: '待处理', type: 'warning' },
      DONE: { label: '已处理', type: 'success' },
      IGNORED: { label: '已忽略', type: 'info' },
    },
    stockWarning: {
      NORMAL: { label: '正常', type: 'success' },
      LOW: { label: '低库存', type: 'warning' },
      HIGH: { label: '高库存', type: 'danger' },
    },
    stockStatus: {
      ACTIVE: { label: '正常', type: 'success' },
      FROZEN: { label: '库存冻结', type: 'warning' },
      OFFLINE: { label: '库存下线', type: 'info' },
    },
    operationResult: {
      SUCCESS: { label: '成功', type: 'success' },
      FAILED: { label: '失败', type: 'danger' },
    },
    alertLevel: {
      HIGH: { label: '高风险', type: 'danger' },
      MEDIUM: { label: '中风险', type: 'warning' },
      LOW: { label: '低风险', type: 'info' },
    },
    productStatus: {
      DRAFT: { label: '草稿', type: 'info' },
      OFFLINE: { label: '下架', type: 'warning' },
      ONLINE: { label: '上架', type: 'success' },
      VIOLATION: { label: '违规', type: 'danger' },
      OFFLINE_VIOLATION: { label: '违规下架', type: 'danger' },
      RECOVER_ONLINE: { label: '恢复上架', type: 'success' },
    },
    adminAccountStatus: {
      ENABLED: { label: '启用', type: 'success' },
      DISABLED: { label: '禁用', type: 'danger' },
    },
    userAccountStatus: {
      ENABLED: { label: '启用', type: 'success' },
      DISABLED: { label: '禁用', type: 'danger' },
    },
  };

  return maps[kind]?.[normalized] || { label: value || '-', type: 'info' };
}
